### ISSUE TITLE
PHP files not recognized as PHP when first line isn't <?php

### ISSUE THREAD

**Issue by rugk** [atom/language-php#101]
This is related to https://github.com/atom/language-php/issues/48 AFAIK. For example if I save a file with the file extension .php which starts with `<!DOCTYPE html>` because at first it displays some HTML the next time I open it it will be recognized as HTML. (as I can see from the selector at the left right and the syntax highlighting).

Only after I added `<?php` as the first line it was displayed correctly. And strangely this stayed like this although I now replaced the first line with `<!DOCTYPE html>` (again).

Other related issues: https://github.com/atom/language-php/issues/86

**Comment by rochapablo** [comment]
Is that possible create a PHP file and not use the <?php tag?

**Comment by rugk** [comment]
> Is that possible create a PHP file and not use the <?php tag?

It is not, but there can be other (HTML) code before the PHP code starts, so `<?php` does not have to be on the **first line** of the file.

**Comment by rochapablo** [comment]
I got it, but unfortunately that is not want. Thanks anyway.

**Comment by rugk** [comment]
FYI there are also short tags in PHP, but they should not really be used: https://stackoverflow.com/questions/200640/are-php-short-tags-acceptable-to-use
(`<?=` is acceptable though)

**Comment by charlesmudy** [comment]
So whats the solution to this?

**Comment by rochapablo** [comment]
@rugk i know about those tags. I've just would like to know if it was possible recognize the php code only by the file type .php. But in all IDE i guess that's no possible.

**Comment by charlesmudy** [comment]
I finally solved it using https://github.com/execjosh/atom-file-types and doing: 
`'file-types':  'php': 'text.html.php'`

**Comment by rochapablo** [comment]
@charlesmudy I did, but nothing happened.

**Comment by charlesmudy** [comment]
![screen shot 2015-10-26 at 3 37 27 pm](https://cloud.githubusercontent.com/assets/1445007/10731842/8ed8eff8-7bf7-11e5-89a0-1f842085b754.png)

My setup if it helps, do you have similar?

**Comment by rochapablo** [comment]
@charlesmudy yes, that's right. And I named my file as file.php.

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.4.0-beta0.  If it isn't please comment here!
