### ISSUE TITLE
Markdown snippets are not syntax highlighted (in preview)

### ISSUE THREAD

**Issue by rugk** [atom/language-php#104]
See https://github.com/atom/markdown-preview/issues/307

I'm just reporting this here too, because I don't know which package is more responsible for this.

**Comment by rugk** [comment]
Any news?
@50Wliu in https://github.com/atom/markdown-preview/issues/307#issuecomment-191223356: 
> It does use the PHP grammar, but the grammar doesn't match anything because of the missing <?php.

**Comment by 50Wliu** [comment]
I mean, we could loosen the rules so that a `<?php` isn't required, but I'm not sure that would be the best way.  Maybe we could create a new pseudo-grammar that's used for Markdown.

**Comment by mickenorlen** [comment]
I want to remove the <?php tag requirement too for working with TYPO3 extensions.

**Comment by 50Wliu** [comment]
Closing in favor of #182, which has slightly more discussion.

**Comment by 50Wliu** [comment]
Turns out that language-gfm was using the wrong scope in the first place...was using the non-existent `source.php` instead of `text.html.php`.  Fixing that still wouldn't have solved the problem of `<?php` tags being required.  I have pictures/explanations of a possible fix over at #182.
