### ISSUE TITLE
Syntax highlighting with <script> tags

### ISSUE THREAD

**Issue by jrhenderson1988** [atom/language-php#107]
Hi,

Myself (Using Ubuntu) and colleague (Using Mac) are both having issues with the syntax highlighting php and html files with regards to `<script>` tags.

![untitled](https://cloud.githubusercontent.com/assets/8791010/10727882/27768a40-7bd5-11e5-9d58-db8da2598c23.png)

As you can see, in both HTML and PHP files the `<script></script>` and `<script type="text/javascript"></script>` tags are being coloured incorrectly. After the initial `<script` part, everything that should stay white like in other tags, goes an orange colour (Using Peacocks in Space theme).

However I find that if I unindent these two snippets all the way to the beginning of the line they seem to highlight fine. That is until I start adding some content to the `script` tags as seen here:

![untitled2](https://cloud.githubusercontent.com/assets/8791010/10728036/6118d4aa-7bd6-11e5-9439-8c85cd22edd9.png)

My colleague and I use different syntax highlighting themes and I've even tried some of the default Atom themes such as `Atom Dark` and `Atom Light`. The issue persists no matter where in the document I place the script tags and for all kinds of variations e.g. `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" type="text/javascript" charset="utf-8"></script>`

**Comment by Ingramz** [comment]
HTML/JavaScript highlighting is inherited from [language-html](https://github.com/atom/language-html) package. Unfortunately I couldn't find the exact issue number you are experiencing, but I assure you it has nothing to do with PHP grammar.

**Comment by jrhenderson1988** [comment]
I thought that might have been the case. Is there any way I can move this issue to the language-html repository or will I need to recreate the issue over there? Cheers.

**Comment by 50Wliu** [comment]
This looks like it's already been reported: atom/language-html#82, so you can go look over there :).
