### ISSUE TITLE
Callable type hint is identified as class - potential bug?

### ISSUE THREAD

**Issue by Gert-dev** [atom/language-php#108]
Hello

I noticed that the `callable` type hint in functions and methods seems to be identified as a `.support.class.php`. Other type hints for built-in types such as `array` receive a `.storage.type.php`. Is this intentional?

Thanks in advance

**Comment by Ingramz** [comment]
`callable` should also be detected as `storage.type.php`

From what I understand, there has been some time between when `array` and `callable` type hint were introduced into PHP language and noone has picked this up before. This might explain why there is no entry for `callable` in the grammar yet. It should be a fairly easy fix, though.
