### ISSUE TITLE
Highlighting breaks if it is in a HTML comment

### ISSUE THREAD

**Issue by rugk** [atom/language-php#115]
``` php
<!-- html comment start
<?php
// some php stuff which should not be affected by this HTML comment

if ($isBad) {
    echo 'fail!';
} else {
    doSomethingNice($apple, $bananas);
    if (isset($awful)) {
        phpversion();
    }
}
?>
html comment end -->
```

![htmlcommentphpbreak](https://cloud.githubusercontent.com/assets/11966684/12012146/928419c6-ace8-11e5-8684-09d4f582c3f4.PNG)

**Comment by zr9** [comment]
That one exactly as issue #109. Look it please i'm explained in deep why i'm think for now it not supposed to have a fix.

**Comment by 50Wliu** [comment]
Ooh yeah, this one looks ugly...

**Comment by 50Wliu** [comment]
Yep, agreeing with @zr9 here.  This is expected behavior: PHP is _inheriting_ the styles from the HTML comment.
