### ISSUE TITLE
Incorrect grammar with ?x parameter

### ISSUE THREAD

**Issue by zr9** [atom/language-php#122]
@50Wliu Sorry to bother you, but I'm need your help to escalate issue to core atom. Could you please check and confirm next one.

The issue:
x flag is PCRE_EXTENDED supposed to use to format regex, when it used all whitespace should be ignored except when escaped or in character class. Then **#** symbol suppose work as comment, so all characters when this symbol is not in char class should be ignored until newline. And here exactly happens the problem, it seems like newline is ignored until it set as explicitly as "\n". So real new lines looks like ignored.

Here is code for test, code is for scope **meta.function.argument.typehinted.php**

grammar:
```
(?xi)
              \\s*([a-z_][a-z_0-9]*)?
              \\s*(&)? # Reference\n
              \\s*(((?:\\.\\.\\.)?\\$+)[a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*)
              (?:
                \\s*(?:(=)\\s*(?:(null)|((?:\\S*?\\(\\))|(?:\\S*?)))) # A default value\n
              )?
              \\s*(?=,|\\)|/[/*]|\\#|$)
```

php file:
```php
<?php
function test2(classname $param2){

}
?>
```
Remove any "\n" from any of comments, or both, and error appears.
Attaching grammar(code is on line 370) and php test file just for case.

[bug.zip](https://github.com/atom/language-php/files/100124/bug.zip)

**Comment by 50Wliu** [comment]
@zr9 you have to use triple-quotes (`'''` or `"""`)to properly support the extended regex, since triple-quotes span newlines, while single-quotes don't.

**Comment by zr9** [comment]
Oh truly, thats cson. Dumb me, really sorry for that one, and thanks for helping
