### ISSUE TITLE
Broken syntax highlighting on regex with simple quotes

### ISSUE THREAD

**Issue by dobleme** [atom/language-php#124]
The highligtinh brokes when a regex with this form is simple quoted and since the regex until the end of file is hihglighted in red.
With double quotes it works.

![bug-php-syntax](https://cloud.githubusercontent.com/assets/7830854/12813989/e42206be-cb3b-11e5-9e69-2136d98a2c21.png)

The first time I saw was on 1.0.19 version, now I'm using 1.3.3 and still ocurring.

**Comment by lee-dohm** [comment]
I don't think it will fix your issue, but the latest version of Atom is v1.4.3.

**Comment by ericandrewlewis** [comment]
Seeing this in Atom `1.6.2` and language-php `0.37.0`. 

![screen shot 2016-04-08 at 6 46 45 pm](https://cloud.githubusercontent.com/assets/1087646/14399389/42f29748-fdba-11e5-8398-228430399f1a.png)

**Comment by bj7** [comment]
Hey, I stumbled across this as well. Atom v1.7.3. `preg_match('/^(\{|\[|")/'`. I think it also breaks the symbol look up, but I'm not sure since I can't get it to work for my current PHP file. The symbol lookup works for my other PHP files, but since I can't confirm that the symbol lookup is affected by regex, let's assume it's not. That'll be my own bug to figure out.

**Comment by bj7** [comment]
I've narrowed it down a bit more. The error with syntax highlighting seems to come from the `[` in the regex. Removing it clears up the issue. I'm working on a fix in php.cson file, since it appears that the `[` is not matched correctly.

**Comment by bj7** [comment]
Sorry for the long delay in updates, been a busy week. I believe I have fixed it. It had to do with the `constant.character.escape.php` regex not being in the `patterns` array. Originally, it was sitting in
``` coffeescript
'repository':
      'single_quote_regex_escape':
        'comment': 'Support both PHP string and regex escaping'
        'match': '(?x) \\\\ (?: \\\\ (?: \\\\ [\\\\\']? | [^\'] ) | . )'
        'name': 'constant.character.escape.php'
```
which is outside of the `patterns: [...]`. I know `constant.character.escape.php` was being referenced via calls to `include: #single_quote_regex_escape`, but for some reason it wasn't being interpreted correctly. The regex-double-quoted configuration had the `constant.character.escape.php` in the `patters: [...]`. Double quotes worked perfectly, so the obvious thing to do was to include it in `patterns:[...]` for regex-single-quoted.

The image below shows prior to the fix.
![image](https://cloud.githubusercontent.com/assets/1395096/15093385/4e25731e-1454-11e6-871e-c064cd36cb7e.png)

After
![image](https://cloud.githubusercontent.com/assets/1395096/15093394/7702bb16-1454-11e6-94d6-7b1d0ea08f95.png)
Proper syntax highlighting is returned, and the escaped characters are properly accounted for in the regex when viewing through the dev tools:
![image](https://cloud.githubusercontent.com/assets/1395096/15093408/c4f203cc-1454-11e6-9f93-59198cecc4fa.png)

I do not know why the `include: #single_quote_regex_escape` does not work properly. In my updated version, I've removed the `repository` and references to `#single_quote_regex_escape`. If it is necessary to keep the `repository` and its references, then please let me know, but I can't see any issues when removing them.
