### ISSUE TITLE
Possibly incorrect highlighting on PHP 5.5 'class' keyword for classes.

### ISSUE THREAD

**Issue by ghost** [atom/language-php#125]
Hello

The new class keyword introduced in PHP 5.5 is currently being highlighted as 'other constant', though it is really more of a keyword [1]. For example:

``` php
$a = self::class;
$b = static::class;
$c = parent::class;
$d = Foo::class;
```

Thanks in advance

[1] https://wiki.php.net/rfc/class_name_scalars

**Comment by 50Wliu** [comment]
@UziTech @Ingramz pinging you two since you seem knowledgeable with PHP.  Does `constant.language.class.php` sound accurate?  Or, if you would rather prefer a `keyword.*` scope, what should it be named?  Unfortunately, `keyword.operator.class.php` is already taken by `::`.

**Comment by UziTech** [comment]
I think `constant` is correct.

Could we do `keyword.constant.language.class.php`? Or something like that

**Comment by 50Wliu** [comment]
Going with `keyword.other.class.php` since constants generally don't change...but `class` does.
