### ISSUE TITLE
Incorrect highlighting for trait uses inside classes.

### ISSUE THREAD

**Issue by ghost** [atom/language-php#127]
Hello

It seems a couple of things are going wrong when dealing with use statements that contain aliases:

``` php
class Foo
{
    use TraitOneMethod {
        test as private test1;
        TraitOneMethod::method insteadof TraitOneMethod;
    }
}
```

Here, `test`, `as`, `private` and `test1` are all marked as separate `.other.namespace.use` items. `TraitOneMethod` is correctly determined to be a class name, but `method`, `insteadof` and `TraitOneMethod` are all seen as separate `constant`s.

Thanks in advance

**Comment by 50Wliu** [comment]
Adding a link to the documentation because this was harder than expected to find.
http://php.net/manual/en/language.oop5.traits.php
