### ISSUE TITLE
PHP 7 Spaceship operator

### ISSUE THREAD

**Issue by iadj** [atom/language-php#131]
PHP 7's `<=>` operator returns an error in Atom: `syntax error, unexpected '>`

**Comment by Ingramz** [comment]
@iadj looks like your error is related to some other package, which isn't bundled with Atom by default. To be sure, try https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode first and report back.

**Comment by 50Wliu** [comment]
`language-php` only highlights your files and does not attempt to execute them.  A good way of finding out which package is causing your issue is through using the [package-cop](https://atom.io/packages/package-cop) package.

**Comment by iadj** [comment]
@Ingramz @50Wliu Thank you, you're correct. The issue lies with me using an outdated php path with the `php-linter` package.
