### ISSUE TITLE
Inaccurate scopeDescriptor in getSuggestions

### ISSUE THREAD

**Issue by maxwellimpact** [atom/language-php#132]
It seems the auto-complete providers are being sent an inaccurate scopeDescriptor. I've been working on an auto-complete for PHP with better context, and it seems the best way to ensure your scope is accurate is by doing the following in the getSuggestions function.

```coffee
oneBackBufferPosition = bufferPosition
oneBackBufferPosition.column = oneBackBufferPosition.column - 1
scopeDescriptor = editor.scopeDescriptorForBufferPosition(oneBackBufferPosition)
```

This is most notable when typing within ( ) or { } before a new line.
```php
if($badScope == $badScope) go();

function gold($badScope) {return $badScope;}
```

If they are not closed then the scopeDescriptor seems fine.
```php
if($goodScope

function gold($goodScope
```

As I mentioned the above code seems to fix this, but I believe this is an issue either with Atom or the way this package handles the scope. I'm not familiar enough with the Atom internals yet to say for sure.

**Comment by lee-dohm** [comment]
@joefitzgerald do you have any insight into this?

**Comment by joefitzgerald** [comment]
This has to do with bracket matcher. When enabled, typing an opening ( will cause a ) to be automatically inserted. This occurs synchronously so to autocomplete-plus it is like two characters were pasted into the buffer. ac+ already has code treating this as a special case: https://github.com/atom/autocomplete-plus/blob/2ab3051e18cc9b42474700a1739a39fc9b543d0d/lib/autocomplete-manager.coffee#L480

However hiu are right that it is not compensating for this in the set of things provided to an ac+ provider, including the scope. However the scope *is reflective of the current buffer position*. There are two pathways forward here: either have each provider than cares handle this, or try to address it in ac+. My only hesitation on the latter it the current behavior describes the current scope and buffer position and if we special case for this, what other scenarios might we also need to? At least the current behavior (once you understand how bracket matcher works) is easy to reason over.

**Comment by DEV-SOUTH** [comment]
@joefitzgerald thanks for the write up on this. It makes sense. Maybe some added documentation would help clarify this. To me the most sensible thing would be to provide a `scopeDescriptor` that is most useful to the provider, though I think if it is documented those implementing a provider can handle.

**Comment by maxwellimpact** [comment]
@joefitzgerald thanks for the write up on this. It makes sense. Maybe some added documentation would help clarify this. To me the most sensible thing would be to provide a scopeDescriptor that is most useful to the provider, though I think if it is documented those implementing a provider can handle.

**Comment by joefitzgerald** [comment]
@maxwellimpact maybe we should update the wiki page for the provider API, or create a new one and link to it from the provider API page?

**Comment by lee-dohm** [comment]
I took the liberty of creating a new Issue on the autocomplete-plus repository for the documentation. Since it doesn't sound like this is an issue specific to language-php, I'm going to close this.

Please let me know if there is something that I missed @maxwellimpact :grinning:

**Comment by maxwellimpact** [comment]
@lee-dohm sounds great.
