### ISSUE TITLE
Heredoc issue

### ISSUE THREAD

**Issue by Asdra** [atom/language-php#133]
Hi, I noticed another issue with heredoc syntax, it seems that highlighting breaks when it meets a `'`, here is an example :

![bug_atom_1](https://cloud.githubusercontent.com/assets/7705276/14778787/3cd848bc-0ad5-11e6-8bbf-39f23aef244d.png)

The entire file is not highlighted after this bug.

**Comment by Ingramz** [comment]
This is not a completely different issue, just a side effect of the current issue at hand. Everything after the first `<` is parsed like source code, orange being constants. If heredoc worked, we wouldn't have this issue.

At the pointed location you begin a string which will be never closed, so it interprets rest of the file as string. To work around this, you could end the heredoc like this: `HEREDOC; // '` which will close the opened string.

**Comment by Aldlevine** [comment]
:+1:

**Comment by sscotti** [comment]
Anyone ever make any progress on this.  I just discovered and it is pretty annoying.  If I want to include CSS in the HEREDOC string the "#" for Id's breaks the formatting, comments out everything that follows.

**Comment by 50Wliu** [comment]
Fixed by #184.
