### ISSUE TITLE
No highlights inside HTML tags

### ISSUE THREAD

**Issue by TamasDukai** [atom/language-php#144]
Hi,

The syntax of my php code isn't highlighted inside <html></html>

**Comment by joshvickerson** [comment]
Duplicate of #115?

**Comment by 50Wliu** [comment]
There is currently not enough information to triage this issue.  @TamasDukai please read [How Do I Submit a (Good) Bug Report?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) and then file a new issue.
