### ISSUE TITLE
Syntax highlighting in class method - default value

### ISSUE THREAD

**Issue by coolfocks** [atom/language-php#148]
Hello,

When writing default value for variable which is of a certain type (string, int, bool) - not array, the default value gets highlighted red as if it was wrong. When I dont specify type of variable, it does not highlight the default value red. When I specify that type is for example class Foo and default value is null, it does not get highlighted red.
![image](https://cloud.githubusercontent.com/assets/6826579/17014695/2ba37798-4f26-11e6-9e60-127b71a2d549.png)

When inspected using dev tools
![image](https://cloud.githubusercontent.com/assets/6826579/17014714/4e31abc2-4f26-11e6-8023-28b133d99580.png)

I would appreciate any feedback on this, if others can replicate this problem I could offer my help with fixing it.

Thanks in advance, Tom

**Comment by JanGalek** [comment]
It write me "Default value for parameters with a class type hint can only be NULL", so only change a rule for need NULL.

**Comment by 50Wliu** [comment]
```php
public function render(int $limit = 20) : string {
  return '';
}
```

**Comment by 50Wliu** [comment]
Actually, closing in favor of #178 which has a bit more information and examples.
