### ISSUE TITLE
PHP 7 (new) ternary condition support

### ISSUE THREAD

**Issue by clota974** [atom/language-php#149]
Hi,
In PHP 7 a new syntax has been introduced for the ternary conditions as said [here](http://php.net/manual/en/language.operators.comparison.php).
It is : `$a = true??false;`
But Atom doesn't support this syntax, and triggers "Parse error".
It'd be great to update the PHP language, or to tell me how to remove that error.
Thanks, Killian.

**Comment by Ingramz** [comment]
Hi. Does Atom trigger a "Parse error" if you run Atom in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by clota974** [comment]
No, it doesn't trigger a parse error because even if I forget a semi-colon or anything else, it doesn't trigger any error at all.

**Comment by Ingramz** [comment]
If you say that it's fine in safe mode, then the issue must be somewhere else.

Please show which packages you have installed using `apm list --installed`

**Comment by 50Wliu** [comment]
Closing as this issue does not occur in safe mode.  Feel free to continue discussion here though.

**Comment by clota974** [comment]
Here are my packages : 
├── activate-power-mode@0.7.0
├── aligner-python@1.0.1
├── autoclose-html@0.23.0
├── autocomplete-jquery-mobile@0.2.2
├── autocomplete-php@0.3.7
├── browser-refresh@0.9.0
├── css-edit-groups@0.4.2
├── css-snippets@0.9.0
├── drunken-php@0.2.1
├── emmet@2.4.3
├── jQuery@1.2.4
├── killian-syntax@0.0.0
├── linter@1.11.14
├── linter-php@1.2.0
├── pigments@0.31.2
├── sass-autocompile@0.12.8
├── seti-syntax@1.0.1
├── seti-ui@1.3.1
├── syntax-theme-auto-changer@0.9.4
└── tool-bar@1.0.0

└── (empty)

**Comment by Ingramz** [comment]
@clota974 most likely it is `linter-php@1.2.0` that is causing you issues. Perhaps you have an old version of php installed? You can verify by running `php --version` or check where you have configured the PHP path to be in `linter-php` settings.

**Comment by clota974** [comment]
Indeed, I have an old version of PHP :(
As MAMP was using PHP 7.0, I thought it was this same version everywhere.
Thank you :)
