### ISSUE TITLE
Highlighting fails inside HTML attributes.

### ISSUE THREAD

**Issue by odahcam** [atom/language-php#151]
`PHP` highlighting fails inside `HTML` attributes.

The problem occours in Atom Dark, Base16, or any other theme. I see the same on VisualStudio Code.

**Atom:**
![image](https://cloud.githubusercontent.com/assets/3942006/17981852/d1246530-6adb-11e6-8d55-f97935697133.png)

**VS Code:**
![image](https://cloud.githubusercontent.com/assets/3942006/17981884/f32c6966-6adb-11e6-8269-b1b1799fa535.png)

**Sublime Text 3:**
![image](https://cloud.githubusercontent.com/assets/3942006/17981834/bab88cae-6adb-11e6-9c7f-b3c6b1f4431a.png)

As you can see, Sublime highlights the `CSS` inside `style` attribute too, would be nice if Atom did the same, but this is content for another issue.

The `PHP` highlighting also fails inside comments (#115).

I'm using the `<?=` shortcode for `<?php echo`, but the issue occours with both notations.

**Comment by Ingramz** [comment]
Could you post an image of the same snippet of code using "Atom Dark" syntax theme? This would give us a baseline to work on.

**Comment by odahcam** [comment]
Unfortunately (or not) it's ok in other themes, but I'm using my PC now (other SO, other monitor, other graphics card, etc), it could be a color profile problem or just a mistake.

**One Dark:**
![image](https://cloud.githubusercontent.com/assets/3942006/17988358/1e25ebfe-6afc-11e6-84b2-3ce4fa103ea0.png)

**Atom Dark:**
![image](https://cloud.githubusercontent.com/assets/3942006/17988370/3ce4f62a-6afc-11e6-98a9-af666106479e.png)

**Material:** (custom theme)
![image](https://cloud.githubusercontent.com/assets/3942006/17988392/5b2e5e3c-6afc-11e6-8276-3847cf1e90f2.png)

I think it's all right with the highlighting  with these themes. How can I work on these themes by myself?

**Comment by Ingramz** [comment]
Themes are basically stylesheets, if you know CSS, then it should be trivial.

If you need class names for different elements, toggle developer tools and use inspector. It is useful for finding how other themes do something as well.

Here are the themes that you say it's ok with.

https://github.com/atom/one-dark-syntax
https://github.com/atom/atom-dark-syntax

This should be the place you are interested in https://github.com/atom/atom-dark-syntax/blob/8da6bdbb0438e91fa901caa0d0073533ab86f92e/index.less#L175-L180

**Comment by odahcam** [comment]
Perfect, thank you!

I made my version: https://github.com/odahcam/atom-monokai-syntax/ (not published to Atom amp yet)

**Comment by 50Wliu** [comment]
Closing as this is a theming issue.

**Comment by designcise** [comment]
The solution proposed via theme does not quite work for me; I'm using php short tags <?= ($something) ? '' : " attribute="$some_var"; ?> try something like that (in say, a template file (.tpl, .inc, etc.) and it breaks. Changing the language to PHP fixes this. I think there needs to be a "file type association" setting in the settings panel for this.

**Comment by Ingramz** [comment]
@designcise this is a completely different issue. Also `inc` are detected by Atom out of the box. `tpl` files however are not. If you want, you can easily add it to your own config or make a pull request and add it to the list at the beginning of `grammars/php.cson`.

Here's the snippet you can add to `File->Config...`
```cson
customFileTypes:
  'text.html.php': ['tpl']
```

**Comment by bastivogt** [comment]
`  "core":
    "customFileTypes":
      "text.html.php": ["html5"]`
