### ISSUE TITLE
Syntax highlighting breaks if you use php inside javascript

### ISSUE THREAD

**Issue by octoxan** [atom/language-php#161]
```php
<script type='text/javascript'>
var foo = '<?php echo $foo; ?>';
</script>
```

Every bit of code after this has broken syntax highlighting

**Comment by Ingramz** [comment]
@octoxan broken how? Could you please provide a screenshot and version of Atom you are using.

**Comment by octoxan** [comment]
I'm on version 1.12.0-beta0, it just started on this version. Problem didn't happen before updating.

I can also confirm that it does this for every syntax theme I have installed, including default/included ones. Both files are recognized as PHP in the bottom corner.

Example of correct syntax highlighting: 

![good-syntax-highlighting](https://cloud.githubusercontent.com/assets/4382195/19322232/3388507c-9086-11e6-837b-1a45d257dc11.png)

Example of a file that has php inside of script tags

![bad-syntax-highlighting](https://cloud.githubusercontent.com/assets/4382195/19322254/43fd6870-9086-11e6-9090-2f99588174bb.png)

**Comment by Ingramz** [comment]
@octoxan how does that relate to the snippet you posted earlier? Can you show it from the point where the highlighting breaks?

**Comment by octoxan** [comment]
D'oh I figured it out. It was when I was using
```php
var events = <?php echo $this->getEventJson();?>;
```

and seems to only be breaking because that php is going to create the quotations, so it missing the quotations was throwing off everything.

I guess its a non issue, and is just related to weird Magento php.

Sorry!

**Comment by 50Wliu** [comment]
Also, there was a general issue where PHP just flat-out didn't work in embedded JavaScript.  This should start working properly in Atom 1.13.0.
