### ISSUE TITLE
Can't extend language php package

### ISSUE THREAD

**Issue by frytyler** [atom/language-php#162]
Hi all, 

Internally at our company we've standardized our style of commenting functions to build out our documentation. Something similar to doc blocks however it's the same style in PHP and JS. I would like to create a Language / Grammar package for Atom that basically fully extends this language-php package but allows me to write some custom patterns for our comments. 

I have tried to put block below in my own .cson file and I can't get it to pull in no matter what I try. Strange thing is that I can pull in other sources no problem. I can pull in text.html.basic or source.json, source.coffee etc. Not sure if there is some restriction on this package that it cannot be included or not. 

```cson
patterns: [
  {
    include: 'text.html.php'
  }
]
```

Sample of the comment I'm trying to highlight. (Basically CSON inside a full comment)

```php
/*
  'Function Name': 'myFunction'
  'Description': 'some description'
*/
```

Any insight you can provide is much appreciated.

**Comment by Ingramz** [comment]
Related https://github.com/atom/first-mate/issues/40

**Comment by frytyler** [comment]
Thanks @Ingramz, it's too bad that there's no way to extend it. So strange that it works for other core languages. 

I may have to fork it and try and keep it up to date with this as much as possible.

**Comment by 50Wliu** [comment]
Closing in favor of atom/first-mate#40.
