### ISSUE TITLE
PHP in <script> tag breaks color syntax.

### ISSUE THREAD

**Issue by Cronick** [atom/language-php#168]
Seems like this recently happened, as it was working just fine yesterday, so seems like Atom has updated by itself on some part.

Image with PHP in script - https://vgy.me/TMO0n4.png
Image without PHP in script - https://vgy.me/0U818E.png

But as you can see on the images, it seems to mess with the color syntax, because of the php code in the <script> tag. I have tried with <?php ?> and the result is the same.

I have version 0.37.3 of language-php installed. I have also tried to change color syntax, and the result is the same.

**Comment by 50Wliu** [comment]
This should be fixed starting in Atom 1.14.0.
