### ISSUE TITLE
Syntax Highlighting Issue: script tags when PHP is inlined within the tags.

### ISSUE THREAD

**Issue by kendalltristan** [atom/language-php#169]
Using Atom 1.12.2 and language-php 0.37.3 on Arch Linux. I've duplicated the issue with Atom 1.12.3 and language-php 0.37.3 on OS X. The issue is present regardless of theme.

I'm having an issue where the closing </script> tag and all subsequent HTML tags lose syntax highlighting if a block of PHP code is inserted within the <script></script> block. See here:

[Issue](http://i.imgur.com/3IWR4XQ.png)

When I remove the inline PHP, the issue goes away. See here:

[No PHP, No Issue](http://i.imgur.com/GUFzb2Y.png)

The issue appears to be associated with the presence of the <?php ?> tags as shown here:

[Empty PHP Tags](http://i.imgur.com/XgLGHtk.png)

To quickly demonstrate and duplicate the issue, enter the following in a new file with PHP syntax highlighting:

```
<div>
<script>
<?php ?>
</script>
</div>
```

The expected behavior would be that the closing script tag and following HTML tags would retain their default highlighting.

Thanks a bunch.

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.14.0.
