### ISSUE TITLE
PHP Highlighting broken after & in URL href

### ISSUE THREAD

**Issue by willihangga** [atom/language-php#170]
## Description
Comment Highlighting broken in PHP mode with `&` in URL href. [ Link to screencap](https://cldup.com/yPYxxIZWnV.png)

**Expected behavior:** The `&` highlight should not break beyond `&` character. [ Link to screencap](https://cldup.com/PtEWvC_uO7.png)

**Actual behavior:** Highlight continues beyond `&` character. [ Link to screencap](https://cldup.com/yPYxxIZWnV.png)

## Versions
1.11.2 and earlyer

**Comment by Ingramz** [comment]
Actually this issue should belong to `language-html` repository.

`&` is a reserved character for displaying other reserved characters. So actually the correct way of using ampersand would be `&amp;` just like `&nbsp;` is for a non breaking space, which you might have seen before.

Either way, the behavior you have shown has been mitigated in 1.12, so simply updating your Atom installation should already solve most the issue you are having.

**Comment by 50Wliu** [comment]
To clarify, this should be fixed in the upcoming 1.12.5 release.

**Comment by willihangga** [comment]
I can confirm it has been fixed in 1.12.5
