### ISSUE TITLE
syntax highlighting error

### ISSUE THREAD

**Issue by gabystallo** [atom/language-php#171]
When inserting PHP code inside a <script> block, syntax highlighting of the rest of the document goes wrong. It started happening a few days ago!

![captura de pantalla 2016-11-21 a las 1 16 32 p m](https://cloud.githubusercontent.com/assets/2278916/20490459/d84eb044-afec-11e6-8981-4f7b0f39e8d7.png)

**Comment by 50Wliu** [comment]
This has been fixed and will be available in Atom 1.14.0.
