### ISSUE TITLE
Syntax Highlighting - PHP inside Javascript Code

### ISSUE THREAD

**Issue by ADTC** [atom/language-php#176]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).
    * Followed all applicable steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/).
    * Checked the [FAQs](https://discuss.atom.io/c/faq) on the message board for common solutions.
    * Checked that your issue [isn't already filed](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom).
    * Checked that there is not already an [Atom package](https://atom.io/packages) that provides the described functionality.

### Description

The Syntax Highlighting of the file goes awry when there's a PHP code block inside a JavaScript block. Please see the following screenshots of what's happening:

![image](https://cloud.githubusercontent.com/assets/6047296/21472310/6a080dbe-cb0e-11e6-8672-cc67e835c327.png)

In the **first** screenshot, we just have HTML and JavaScript code. The highlighting seems to be proper, although I'm not sure why the opening script tag is orange (is that a feature?).

In the **second**, we have added a PHP code block right in the middle of JavaScript code. Now the syntax highlighting has broken.

In the **third**, we added an extra question mark. As an example, I have added the question mark after `oh`, but it doesn't matter where I add the extra question mark within the PHP code block. As long as this third question mark is there, the syntax highlighting is somehow "fixed". Of course, the PHP code itself may not be valid with the addition of extra question mark. And it makes no sense to add an unnecessary question mark to the source just to fix syntax highlighting in the editor.

Side note: I have noticed that when the PHP code block is in the midst of regular HTML, the issue does not occur. The choice of quotes between single (`'`) and double (`"`) doesn't seem to make any difference. The issue can also be fixed by putting `?>` in a new line. But this means single-line PHP codes can't be used without breaking the syntax highlighting. The issue is also reproducible with the `<?=$variable?>` syntax.

This might be related to the HTML language syntax highlighting, since the PHP one is piggybacking on it. _I'm not sure._ In HTML mode (see screenshot below), if you add a PHP code block, naturally the highlighting breaks. It's not a problem there since PHP is unexpected in HTML. However, **notice the similarity between the two modes**. In PHP mode, the syntax highlighting breaks the same way as it does in the HTML mode. The difference is that the extra question mark "fixes" the breakage in PHP mode, while (understandably) doing nothing in HTML mode.

![image](https://cloud.githubusercontent.com/assets/6047296/21472309/6014f1aa-cb0e-11e6-9d23-2128595018bb.png)

### Steps to Reproduce

1. Type the different code examples (see below)
2. Try PHP mode or HTML mode

**Expected behavior:** Properly highlight the syntax

**Actual behavior:** Does not recognize the closing tags correctly hence does not properly highlight the syntax

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. 

```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git 2.10.0.windows.1
visual studio
Windows 10 Version 1607 (OS Build 14393.576)
```

### Additional Information

I'm using the Atom Dark theme for both UI and Syntax. I have very minimal customization, and I can reproduce in safe mode.

Here's the code block for your convenience:

```
<!doctype html>
<html>
<head>
  <title>untitled</title>
</head>
<body>
  <script>
  var test = 'Some JS';
  <?php $test = 'oh?'; ?>
  </script>
</body>
</html>
```

**Comment by ADTC** [comment]
Any idea how this can be fixed? Perhaps the detection of a single-line PHP code block in the PHP mode is not working correctly.

**Comment by Ingramz** [comment]
@ADTC [search is your friend](https://github.com/atom/language-php/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20script).

**Comment by ADTC** [comment]
Glad to know there were issues reported on this @Ingramz but they are all closed, and I don't find any open issue on the same. But this bug still exists in the latest release version, so the closed issues are not going to help fix the existing bug. (Besides, I cannot open a closed issue.)

**Comment by Ingramz** [comment]
@ADTC they are all closed because they have been solved. Most of the issues have been closed with explanation that it has been fixed in the upcoming Atom release 1.13.0, which is in beta right now. You reported your atom version to be 1.12.7 which is lower than 1.13.0.

**Comment by lee-dohm** [comment]
@50Wliu is this fixed by one of the upcoming changes?

**Comment by kingkool68** [comment]
I had a similar issue and opening up the beta version of Atom things seemed fix 👍 

Stable (Note the closing `</script>` tag)
![screen shot 2016-12-29 at 10 21 52 pm](https://cloud.githubusercontent.com/assets/867430/21559179/6d1457d8-ce15-11e6-8105-58bd2d6e65ec.jpg)

Beta
![screen shot 2016-12-29 at 10 22 15 pm](https://cloud.githubusercontent.com/assets/867430/21559180/78a22e0e-ce15-11e6-8c8d-f0321fc2d8b0.jpg)

**Comment by ADTC** [comment]
My bad. Thank you for pointing it out. So the question is, when can I expected this new version to be released? I don't want to beta it at the moment.

**Comment by lee-dohm** [comment]
@ADTC We don't publish ETAs for when we will release future versions of the application.

**Comment by 50Wliu** [comment]
Yes, it has been fixed in Beta.

**Comment by ADTC** [comment]
@50Wliu Since you keep getting a lot of issues with this same problem, isn't it better that you keep this issue or another similar open until v1.13 is released as public?

If you think about it, GitHub defaults to searching only open issues, and people looking to report problems may not think about searching closed issues. I think the expected flow is, you fix the issue, you test the fix in beta, **you release the fix** and _**then**_, you close the issue.

It would be counter-productive to close the issue before the fix is released, because users still on release version looking for open issues before opening a duplicate may not find the closed issue.

As for tracking issues that are already fixed in beta, labels provide an excellent alternative.

**Comment by 50Wliu** [comment]
The problem with leaving issues open is that it's common to forget about it.  In addition, most people don't bother reading through all the comments.  They see that it's open, comment "+1" or similar, and that's it (in fact, this even happens with closed issues...but not as much, thankfully).  In the end, they don't realize that it's actually been fixed already.  You might also notice that the search URL that the issue template provides searches through both open and closed issues.

**Comment by ADTC** [comment]
Valid points there.

+1 😜
