### ISSUE TITLE
Highlighting error argument with value and type set in function

### ISSUE THREAD

**Issue by oopen** [atom/language-php#178]
![atom-bug-false-error-report-in-function-argument-with-value-and-type-set](https://cloud.githubusercontent.com/assets/7348132/21715071/c47804fa-d402-11e6-8028-6579715c084e.jpg)

**Comment by pcfutures** [comment]
+1

**Comment by HansVaider0815** [comment]
Sometime its breaks the whole highlighting (tested in safe mode)!
![image](https://cloud.githubusercontent.com/assets/25368034/24404043/d6b94a46-13bf-11e7-978d-b9019139d99d.png)


If I remove the type hints all is fine:
![image](https://cloud.githubusercontent.com/assets/25368034/24404116/36136490-13c0-11e7-8a92-168a5cc243a2.png)


Reproducible  with this code:
``` php
<?php

function foo(string $subject = "(No Subject)",string  $body = ""){
  echo "This is broken!";
}

?>
```

**Comment by sybrew** [comment]
Unfortunately, I'm still experiencing this issue. Is this a case of regression or isn't the fix public yet?

**Comment by Ingramz** [comment]
@sybrew the fixes should be in beta. If you are using stable, then you'll need to wait.
