### ISSUE TITLE
HTML attributes affect PHP syntax highlighting

### ISSUE THREAD

**Issue by SpectralKH** [atom/language-php#179]
### Description

The syntax highlighting is different if you put PHP code inside HTML attribute values. It gets the colors from the HTML attribute values (Basically the color used in all strings, I guess). In the pictures below, a semicolon and a PHP function is affected.

![screen shot 2017-01-25 at 3 15 07 pm](https://cloud.githubusercontent.com/assets/11315492/22294081/3fc2553e-e312-11e6-96ad-dc4f7541931c.png)
![screen shot 2017-01-25 at 3 14 48 pm](https://cloud.githubusercontent.com/assets/11315492/22294084/415f06f8-e312-11e6-8353-96c31316ba46.png)

### Steps to Reproduce

Make a PHP function inside a HTML attribute value.

**Expected behavior:** Syntax highlighting to be equal

**Actual behavior:** Syntax highlighting takes colors from the HTML string

**Reproduces how often:** Always

### Versions

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1

**Comment by Ingramz** [comment]
That's to be expected and has more to do with the theme that is used. Basically the characters that turned green inside the attributes do not have a specific color associated with them (they are the same color as the plain text outside the attributes). The theme sets a new default color for text inside attributes and everything that was unstyled now has a new default color.

For comparison see how it looks in Atom Dark syntax theme.

**Comment by SpectralKH** [comment]
@Ingramz I see. I initially tried it with One Dark, and that had the same result, and it did, thus I thought it was not theme-related. Thanks for explaining.
