### ISSUE TITLE
Multiline function headers do not highlight the last parameter

### ISSUE THREAD

**Issue by rabbitfang** [atom/language-php#188]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When defining a function/method where the function's parameter list spans multiple lines, the last parameter is not highlighted unless it is given a type and/or default value.

![screen shot 2017-03-08 at 4 16 27 pm](https://cloud.githubusercontent.com/assets/2784296/23726825/54ac91ba-041b-11e7-8125-c787464f5739.png)

### Steps to Reproduce

1. Create a `.php` file with the following content:
```php
<?php

function example(
    $firstArgument,
    $secondArgument
) {
    // No highlighting on the $secondArgument
}

```

**Expected behavior:** `$secondArgument` should be highlighted in red, like `firstArgument`.

**Actual behavior:** `$secondArgument` is not highlighted.

**Reproduces how often:** Always.

### Versions

`language-php`: 0.37.3

```
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.1
```

### Additional Information

As you can see from above, the highlighting problem does not occur when the parameter is given a specific type or a default value. Tabs vs. spaces make no difference.

**Comment by rsese** [comment]
Though it mentions class methods specifically, looks like the same issue as https://github.com/atom/language-php/issues/91?  I.e. when I remove the newline between the last parameter and the closing parenthesis like this:

```php
<?php

function example(
    $firstArgument,
    $secondArgument) {
    // $secondArgument is highlighted
}
```

The last parameter is highlighted.

Going to go ahead and close as a dupe but please re-open if I mis-understood anything.

**Comment by rabbitfang** [comment]
@rsese Nope. Missed that issue when I was looking for existing issues. This is a duplicate of #91.
