### ISSUE TITLE
PHP 7 return-values

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#197]
![image](https://cloud.githubusercontent.com/assets/11234139/26013613/846cad9c-3759-11e7-9123-21459d6c0106.png)

I expect that `Client` as return-value has the same color as the `client` while instantiating it. (and not a const)

**Comment by 50Wliu** [comment]
The return value is now scoped as `storage.type.php`.  This is still different from the instantiation, but I think the scope accurately reflects what its purpose is.

**Comment by jens1o** [comment]
Thanks!
