### ISSUE TITLE
assistance with coding to PSR-1 and PSR-2 standard

### ISSUE THREAD

**Issue by jokeyrhyme** [atom/language-php#20]
http://www.php-fig.org/psr/psr-1/
http://www.php-fig.org/psr/psr-2/

It would be terrific if Atom were able to automatically adjust code to be compliant with the above PSRs.

This is different to linting. I don't want Atom to tell me that my code is non-compliant (well, I do, but that's a separate issue). When typing in class and function braces, Atom should automatically move the open brace to the next line, etc.

It should also make sure indenting and line-feeds are per-specification.

**Comment by andela-gjames** [comment]
This is 2016, is there an Atom package that helps you fix PHP code to PSR standards

**Comment by chrisjimallen** [comment]
@andela-gjames awesome, that would be super helpful if you added a link to it.

**Comment by Ingramz** [comment]
@chrisjimallen @andela-gjames check out linter and linter-phpcs packages.
