### ISSUE TITLE
Colors not display correctly - PHP JS (json_encode)

### ISSUE THREAD

**Issue by aeschli** [atom/language-php#201]
_From @baltazaroliveira on May 12, 2017 15:13_

Steps to Reproduce:

1. For example do this line |
```php
<script type="text/javascript">
        var arr_locais_js        = <?php echo json_encode($arr_locais) ?>;
        var arr_locais_js        = <?php echo json_encode($arr_locais) ?>;
</script>
```
In JS is OK.

In VSCode appeares like that..

![image](https://cloud.githubusercontent.com/assets/953742/26004481/f200dfb2-372d-11e7-90dc-ac054ee4bf27.png)

Please fix this error.

Thanks,
Baltazar

_Copied from original issue: Microsoft/vscode#26560_

**Comment by aeschli** [comment]
_From @egamma on May 12, 2017 15:23_

@baltazaroliveira cannot reproduce or it is not clear from your description what is wrong.

What do you mean by is OK in JS?

In JS

![image](https://cloud.githubusercontent.com/assets/172399/26004928/bb5d81d6-3737-11e7-9cfb-e41ffa134779.png)


In HTML
![image](https://cloud.githubusercontent.com/assets/172399/26004897/9ea5d2be-3737-11e7-8e1b-c35035089f19.png)

In PHP
![image](https://cloud.githubusercontent.com/assets/172399/26004877/90e15478-3737-11e7-9434-1bb7aae303d7.png)

In PHP

**Comment by aeschli** [comment]
_From @baltazaroliveira on May 12, 2017 16:5_

The bug only happens when using json_encode

![image](https://cloud.githubusercontent.com/assets/953742/26006663/32c19d50-3735-11e7-9c4c-8982481a903f.png)

What i do mean Ok in JS, is that i receive the data correctly.

**Comment by 50Wliu** [comment]
Cannot reproduce:
![image](https://cloud.githubusercontent.com/assets/2766036/26653358/e3f47dbe-4620-11e7-86ba-d32dd791c483.png)

Please make sure your textmate engine supports injection prefixes.

**Comment by baltazaroliveira** [comment]
Can you explain what you want to say with "Please make sure your textmate engine supports injection prefixes."?

I´m having the same bug.

![image](https://cloud.githubusercontent.com/assets/953742/26715965/898c8a38-476f-11e7-9366-dc98f433aefb.png)

Thanks
Baltazar

**Comment by 50Wliu** [comment]
This is most likely a bug with VSCode and not language-php.  My comment was directed towards @aeschli.  It looks like vscode-textmate is not respecting the [injections](https://github.com/atom/language-php/blob/master/grammars/php.cson#L40) that language-php is using.

**Comment by baltazaroliveira** [comment]
@aeschli, have you seen this "color bug"? Can you resolve the issue?

**Comment by aeschli** [comment]
@50Wliu I found the problem.
The difference is that VSCode uses the HTML grammar from [textmate/html.tmbundle](https://github.com/textmate/html.tmbundle) which has recently moved away from the scope `source.js.embedded.html`.

The PHP injections rule that textmate now uses is `L:text.html.php source.js`.
 See [here](https://github.com/textmate/php.tmbundle/commit/1d91862a3d118827aa4c0fb57672625a704410c0).

Not sure if is an option for the atom/php grammar to make the same change. IMO the new scope looks better as it makes sure that it's HTML inside PHP.
I'm happy to file an issue if changing the PHP injection is not off the table.

**Comment by 50Wliu** [comment]
I would merge a PR so that language-php also works with VSCode, as long as it also continues working with Atom :).

**Comment by Ingramz** [comment]
As far as I can tell, changing `L:source.js.embedded.html` to `L:text.html.php source.js` simply makes the injection broader, which is unlikely to cause any problems as PHP is supposed to preferred over any other language anyway. If that is what it takes to solve it in VSCode, I would suggest going for it.
