### ISSUE TITLE
Uppercase letters are not considered part of variable in string interpolation

### ISSUE THREAD

**Issue by Ingramz** [atom/language-php#220]
@50Wliu one of the recent commits has broken the following:

```php
<?php
$thisVariableIsFine = "But $thatVariable is not";
?>
```

![ucvar](https://user-images.githubusercontent.com/1017132/27336704-13020960-55d9-11e7-8d29-65301bdbdd04.png)

Update: Possibly caused by [this pattern](https://github.com/atom/language-php/blob/f6462225e76ab54efae04a5b477e803e90f9572c/grammars/php.cson#L3466), which only recognizes lowercase characters.

**Comment by 50Wliu** [comment]
oops

**Comment by 50Wliu** [comment]
Please report any other issues you find!  There might be a few other instances where I forgot to add the case-insensitive modifier.
