### ISSUE TITLE
Static properties and functions are not styled

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#221]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://user-images.githubusercontent.com/11234139/27384034-aed33b2a-568d-11e7-8339-3ab6ae8ef752.png)

### Steps to Reproduce

Write php code:
```php
<?php

Sapi::sendResponse($response);
```

**Expected behavior:** [What you expect to happen]
Styled like it was before the tremendous clean up

**Actual behavior:** [What actually happens]
see screenshot
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

I'm using vscode.

**Comment by jens1o** [comment]
This also affects the class annotation:
![image](https://user-images.githubusercontent.com/11234139/27384400-fdf34f78-568e-11e7-9d96-eb174f59b9c6.png)

**Comment by 50Wliu** [comment]
Hmm...it's working for me, and we also have specs covering it - can you make sure your syntax theme highlights `support.class` and `keyword.operator.class`?

![php-static](https://user-images.githubusercontent.com/2766036/27417240-f6f5f110-56e0-11e7-82dd-9bef351e50fc.png)

**Comment by jens1o** [comment]
Then I think it's a vscode bug? 
![image](https://user-images.githubusercontent.com/11234139/27433151-b5b3a71a-5753-11e7-882f-2d50b059f8c9.png)

**Comment by 50Wliu** [comment]
Yeah, it might be.  We have a lot of specs testing it [here](https://github.com/atom/language-php/blob/e1290265f3d68316347e0ab2665686016b4b24b7/spec/php-spec.coffee#L616).

I would bring it up with the VSCode developers and see what they say :).

**Comment by 50Wliu** [comment]
Looks like this may actually be a bug in first-mate instead :).  It's failing on first-mate@7.0.8 after we fixed a different bug by adhering more closely to the textmate implementation.

**Comment by 50Wliu** [comment]
Fixed.

**Comment by jens1o** [comment]
Thank you! :)
