### ISSUE TITLE
Problems with Namespace\Classname $Variable in a closure

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#222]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
![image](https://user-images.githubusercontent.com/11234139/27388732-9f83d95e-569c-11e7-869d-40ec50981887.png)

### Steps to Reproduce

```php
<?php
$callback = function(FastRoute\RouteCollector $r) use ($routes) {
    foreach($routes as $route) {
        $r->addRoute($route[0], $route[1], $route[2]);
    }
};
```

**Comment by 50Wliu** [comment]
Ironically I tried to avoid changing both the namespace and the closure regexes.  Guess that didn't work out.

**Comment by jens1o** [comment]
Thanks!
