### ISSUE TITLE
function_exists does not work

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#224]
### Prerequisites

* [X] I'm using vscode

### Description

![image](https://user-images.githubusercontent.com/11234139/27514926-46139ea0-5998-11e7-9b23-e4b3f2c504cb.png)

### Steps to Reproduce

```php
<?php

if(!function_exists('json_decode')) {

}
```

**Comment by 50Wliu** [comment]
What exactly is `function_exists`?  Is it a PHP builtin of some sort?

**Comment by jens1o** [comment]
@50Wliu Yes it is. It checks whether a specific function was declared.

**Comment by 50Wliu** [comment]
Finding what seems to be a mistake in the regexes...
`function &test() {}` is not valid, is it?  That is, you shouldn't be able to mark the function itself as passed-by-reference.

**Comment by jens1o** [comment]
no, it's not valid, while `function test(int &$myInt) {}` is valid.
