### ISSUE TITLE
Grouped namespace end bracket is not tokenized

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#232]
### Prerequisites

I'm using vscode.

### Description

![image](https://user-images.githubusercontent.com/11234139/28473059-87c238ba-6e43-11e7-951b-3a8c32a99098.png)

You can see that `};` is not recognized as an ending group and thus can't be styled properly.

![image](https://user-images.githubusercontent.com/11234139/28473068-930f1a1c-6e43-11e7-8f20-0e8c2b7df51c.png)
The beginning bracket has an `support.other.namespace.use.php` property, which is perfectly.

### Steps to Reproduce

```php
use jens1o\webpage\util\{
    AgeDateTime,
    LanguageUtil
};
```

while it works when I do this:
```php
use jens1o\webpage\util\{
    AgeDateTime,
    LanguageUtil};
```
but from my point of view this is ugly.

**Comment by 50Wliu** [comment]
@jens10 is this syntax applicable for uses inside classes (eg #235)?  Also, are the following examples valid?
```php
use one\two\{
  three\four,
  five\six
};
```

```php
use one\two\{
  three\{
    four,
    five
  },
  six
};
```

**Comment by jens1o** [comment]
The first one is valid, the second one isn't.

**Comment by jens1o** [comment]
An tiny example:

```php
<?php

namespace jens1o\hello {
    class Hello {

        public function __construct() {
            echo 'helo';
        }
    }
}

namespace jens1o\hello\world {
    class Hello {
        public function __construct() {
            echo PHP_EOL, __NAMESPACE__;
        }
    }
}

namespace {

    use jens1o\{
        hello\world,
        hello
    };

    new hello\Hello;

    new world\Hello;

}
```
will output:
```
helo
jens1o\hello\world
```
