### ISSUE TITLE
'use' does not support namespaces

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#235]
In investigating https://github.com/Microsoft/vscode/issues/30448, it seems that there is a bug with the grammar. I'm a bit confused since it seems like Atom Beta would have the most recent version of the grammar, but it doesn't actually repro in Atom Beta. When I link in language-php, I can actually repro it in Atom, so it must be on an older version? How do new versions of the grammar flow into Atom?

There are more repro cases in the linked issue, but the bug is basically this- have a 'use' statement inside a class, and that contains a `\`. Everything after it will have the `meta.use.php` scope.
```php
<?php
class Foo {
	use Some\Thing;

	// Comment
	public $name = 'foo';

	public function __construct() {
		$this->doStuff();
	}
}
```

(1) https://github.com/atom/language-php/blob/master/grammars/php.cson#L147 This `meta.use.php` section doesn't match the backslash in `Some\Thing`.

(2) https://github.com/atom/language-php/blob/master/grammars/php.cson#L174 This one is what matches, and only terminates after a `}` (which isn't applicable to this usage of `use`)

(3) https://github.com/atom/language-php/blob/master/grammars/php.cson#L1529 This is the one that should match.

I can help out with a PR, with some guidance as to the best way to fix it. Copy (3) into `class-body`? Change (1) to match `\`?

**Comment by 50Wliu** [comment]
> How do new versions of the grammar flow into Atom?

Atom has three release channels - stable, beta, and dev/master.  The latest PHP improvements are only in master and will be included in the 1.20.0 release.

> I can help out with a PR

Thanks!  What follows is late-night debugging and might be incorrect, so I'll try to re-verify tomorrow morning.  But it looks like L147 is the one that should be matching, so namespace support needs to be added to that one.

**Comment by 50Wliu** [comment]
Yep, here's a quick diff that seems to fix the issue:
```diff
diff --git a/grammars/php.cson b/grammars/php.cson
index f6c6cdb..c37db34 100644
--- a/grammars/php.cson
+++ b/grammars/php.cson
@@ -140,8 +140,8 @@
       {
         'match': '''(?xi)
           \\b(use)\\s+
-          ([a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*)
-          ((?:\\s*,\\s*[a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*)*)
+          ([a-z_\\x{7f}-\\x{ff}\\\\][a-z0-9_\\x{7f}-\\x{ff}\\\\]*)
+          ((?:\\s*,\\s*[a-z_\\x{7f}-\\x{ff}\\\\][a-z0-9_\\x{7f}-\\x{ff}\\\\]*)*)
           (?=\\s*;)
         '''
         'name': 'meta.use.php'
@@ -149,12 +149,15 @@
           '1':
             'name': 'keyword.other.use.php'
           '2':
-            'name': 'support.class.php'
+            'patterns': [
+              {
+                'include': '#class-name'
+              }
+            ]
           '3':
             'patterns': [
               {
-                'match': '(?i)[a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*'
-                'name': 'support.class.php'
+                'include': '#class-name'
               }
               {
                 'match': ','
```

**Comment by roblourens** [comment]
I applied that fix and the same to L174 and it looks correct, but this test case fails -

```php
<?php
class Test {
    use A, B {
        B::smallTalk insteadof A;
    }
}
```

because the first `A` no longer has `support.class.php`. The `#class-name` rule doesn't apply it because it's looking for a `\`.  I tried to fix it and broke something else. Not sure how it's supposed to work.

**Comment by roblourens** [comment]
I guess the third part of the `#class-name` rule doesn't require a `\` but it's not matching and I have no clue why not. This should match the A:

```cson
{
    'begin': '(?=[\\\\a-zA-Z_])'
    'end': '(?i)([a-z_][a-z_0-9]*)?(?=[^a-z0-9_\\\\])'
    'endCaptures':
        '1':
        'name': 'support.class.php'
    'patterns': [
        {
        'include': '#namespace'
        }
    ]
}
```

Anyway if I leave the captures on that L174 rule as-is, then it works as expected. I could prepare a PR with that change at least.
