### ISSUE TITLE
Incorrect color for switch default label when using alt-syntax

### ISSUE THREAD

**Issue by mattacosta** [atom/language-php#236]
*Source: Microsoft/vscode#31320*

### Description
The keyword `default` is white like a regular label instead of purple if it is on a new line, has leading whitespace, and is followed by a colon.

This appears to be a follow-up to #226.

### Steps to reproduce
```php
switch ($a):
  default:
    break;
endswitch;
```

**Comment by 50Wliu** [comment]
Yes, I purposely didn't fix the alternate syntax because I wanted to read up on it some more before attempting a fix.  Thanks for creating the issue though.

**Comment by philraj** [comment]
This is broken using the regular syntax too. All you need to do is put something with brackets in one of your cases:

![screen shot 2017-09-15 at 12 48 05 pm](https://user-images.githubusercontent.com/16470658/30494156-fb99c85a-9a14-11e7-92b4-ed7fa399c8fa.png)

**Comment by 50Wliu** [comment]
@philraj We have a fix for this, it should be merged shortly (#266).
