### ISSUE TITLE
PHP 'instanceof' word.

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [atom/language-php#243]
First of all it is not an issue. Just basic a question. `Instanceof` word isn't highlighted. What should I do?

**Comment by jens1o** [comment]
@BerkhanBerkdemir Can you give us your piece of code?

**Comment by 50Wliu** [comment]
Next time, please fill out the provided issue template, because there's not much I can do to help right now.  Is `instanceof` highlighted in safe mode (`atom --safe`)?  If not, what Atom version are you using?

**Comment by BerkhanBerkdemir** [comment]
![image](https://user-images.githubusercontent.com/24360355/28676628-ccd6475c-72f3-11e7-8bcf-0b0722c61193.png)
@jens1o @50Wliu 

I'm already use standard UI theme (One Light) and syntax theme (One Light).

Finally
Atom version : 1.18.0 x64
language-php : 0.38.0

**Comment by 50Wliu** [comment]
Can you place your cursor on the `instanceof` and execute the `editor:log-cursor-scopes` command?

**Comment by BerkhanBerkdemir** [comment]
![screenshot from 2017-07-28 13-44-47](https://user-images.githubusercontent.com/24360355/28714172-f9eb6b58-739a-11e7-9089-f142407fe828.png)

@50Wliu

**Comment by 50Wliu** [comment]
Thanks.  From the dev tools, it looks like it is receiving the proper scopes, but it looks like one-light-syntax isn't giving it a special color.  You can file an enhancement request here: https://github.com/atom/one-light-syntax
