### ISSUE TITLE
@var array(string) in phpdoc breaks highlighting

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#245]
This snippet
```php
/**
* @var array(string)
*/
$foo = 'bar';
```

causes everything below it to be highlighted as `comment.block.documentation.phpdoc.php`

Top is correct, bottom is not. It seems that the `()` are the problem. This reproes in Atom 1.19 and VS Code.
![image](https://user-images.githubusercontent.com/323878/28696399-28c43c4a-72ea-11e7-8d69-3e720b36faeb.png)

**Comment by jens1o** [comment]
That's not valid fqsen, is it?

**Comment by neerolyte** [comment]
Does it matter? At the moment it leaves the entire rest of the document looking like a comment. Surely the `/* ... */` should take precedence over anything "wrong" in the comment.

**Comment by 50Wliu** [comment]
We attempt to match _valid_ PHPDoc in docblocks.  That's why @jens1o's comment is valid, so I know how to fix this issue.

**Comment by neerolyte** [comment]
Thanks for the clarification. Makes sense now.
