### ISSUE TITLE
Autocomplete snippets does not work

### ISSUE THREAD

**Issue by freestream** [atom/language-php#25]
For example. If i'm in a PHP file and types "/**" the comment snippets does not get activated. Also tried to hit a new line after "/**" but that does not result in a complete snippet.
It would also be a nice feature if i activates the snippet over a function that the snippet reads arguments from the function and automatically adds expected "@params" and "@return" to the comment snippet.

**Comment by 50Wliu** [comment]
Should be resolved with autocomplete-plus/autocomplete-snippets now being bundled in Atom.
