### ISSUE TITLE
Color of code is misleading

### ISSUE THREAD

**Issue by marksagal** [atom/language-php#251]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Take a look at the screenshot I have two "If statement" the first one is from line 14 and the second one is from line 18. The color of "If statement" on line 14 is misleading

![atom-language-php](https://user-images.githubusercontent.com/5668664/28956560-3aa42ec0-7920-11e7-852d-9a3b14dcd69d.PNG)

### Steps to Reproduce
#1 Create a PHP Class
#2 Inside PHP Class create any function and add typehint and default value inside
#3 Inside the class function add if statements

**Expected behavior:**
I Expect that the color of two "IF Statement" is same and consistent.

**Actual behavior:**
It looks like the first "IF Statement" doesn't give proper color

**Reproduces how often:**
On my environment 100%

### Versions
> atom --version
```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
> apm --version
```
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.13.3.windows.1
visual studio
```

### Additional Information

N/A

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.20.0, currently in beta.
