### ISSUE TITLE
if/else alternative syntax colored incorrectly

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#253]
https://github.com/Microsoft/vscode/issues/32142#issuecomment-321169718

PHP supports an alternative syntax for if/else that uses a colon instead of braces: http://php.net/manual/en/control-structures.alternative-syntax.php. In some cases, these are tokenized incorrectly as labels.

```php
<?php

$a = 5;

    if ($a == 5):
        echo "a equals 5";
        echo "...";
    elseif ($a == 6):
        echo "a equals 6";
        echo "!!!";
    else:
        echo "a is neither 5 nor 6";
    endif;
?>
```

When this block is indented, the `else` has `entity.name.goto-label.php`, while if, elseif, and endif are still correct.

If it's not indented, the `else` is tokenized correctly as well.

![image](https://user-images.githubusercontent.com/323878/29136170-422bda1a-7cf1-11e7-8940-6da7e85dd037.png)

**Comment by dwengs** [comment]
I just found that "default" statement in "switch" also does the same thing.
If you indent "default:" word, it colored incorrectly too.
