### ISSUE TITLE
Last function parameter missed by syntax highlighting when using multiple lines

### ISSUE THREAD

**Issue by philraj** [atom/language-php#254]
Sometimes if a function's name is long and it has many parameters who also have long names, I like to break them onto multiple lines. But doing this leads to the last parameter being missed by the syntax highlighting, unless the ending parenthesis is on the same line.

![screen shot 2017-08-10 at 12 28 03 pm](https://user-images.githubusercontent.com/16470658/29181235-5e71923c-7dc8-11e7-9227-e7976d519d67.png)

Adding an empty comment (`//`) after the last parameter also leads to it being highlighted.

Any chance of getting a fix for this?

**Comment by philraj** [comment]
Just a quick follow up: the last argument is highlighted properly if it's typed, i.e.

**Comment by 50Wliu** [comment]
Cannot reproduce, assuming fixed in Atom 1.20.0 (currently in beta).
![php-multiple-params-on-newlines](https://user-images.githubusercontent.com/2766036/29256157-23fb132a-8076-11e7-95eb-97027e956383.png)
