### ISSUE TITLE
Multiline use statement - meta.use.php does not end

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#255]
https://github.com/Microsoft/vscode/issues/32495

Use statements with `\` in a class body was fixed in #235, but a multiline use statement inside a class body breaks colorization.

![image](https://user-images.githubusercontent.com/323878/29284212-a12c391a-80de-11e7-8d5f-33b613874c68.png)

text:
```php
class CompletionProvider
{
  use A\B,
    C\D;

    /**
     * @var DefinitionResolver
     */
    private $definitionResolver;

    /**
     * @var Project
     */
    private $project;
}
```

After the C\D, the `meta.use.php` scope is still applied.

**Comment by 50Wliu** [comment]
This is a very difficult bug to fix.

**Comment by 50Wliu** [comment]
Ok maybe this won't be as difficult as I first thought.
