### ISSUE TITLE
PHP Syntax Break

### ISSUE THREAD

**Issue by Azakur4** [atom/language-php#265]
with the release of language-php v0.41.0 the syntax is broke see this image:

![screen shot 2017-09-12 at 14 39 19](https://user-images.githubusercontent.com/1726914/30340369-adde68f8-97c8-11e7-8f07-e8a9bb57838e.png)

Atom version v1.20.0

**Comment by roblourens** [comment]
Can you include the contents of the file before that snippet? Possibly another instance of https://github.com/atom/language-php/issues/246

**Comment by Azakur4** [comment]
my example is a pure php file and if u see this example in a new file

![screen shot 2017-09-12 at 15 44 28](https://user-images.githubusercontent.com/1726914/30342764-580e3a80-97d1-11e7-8ea5-0abb33794c63.png)

the close bracket is yellow i don't know if that is right

and this happen when i put a use for a trait inside a class

![screen shot 2017-09-12 at 15 46 21](https://user-images.githubusercontent.com/1726914/30342818-8b60860e-97d1-11e7-9edb-49b5ffbfc4af.png)

in version 0.39.0 this doesn't happen

**Comment by Ingramz** [comment]
All highlighting issues described here have been fixed upstream already. Something needs to be done to quickly mitigate issues in stable though.

**Comment by 50Wliu** [comment]
This has been fixed in #257, but I haven't had time to release a new version yet.

**Comment by Azakur4** [comment]
thanks for the fix :D now only waiting for atom patch release
