### ISSUE TITLE
Syntax Highlighting Issues

### ISSUE THREAD

**Issue by RonMelkhior** [atom/language-php#267]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hey, since a recent update some of the syntax highlighting has gone crazy, marking the wrong things.  
Please note that I'm already using version `0.41.1`.

An example:

![Example](https://i.clouds.tf/st16/w758.png)

### Versions

```
>atom --version

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
>apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.13.1.windows.1
visual studio 2015
```

language-php: v0.41.1

**Comment by sybrew** [comment]
When you use properties, this error is also shown in comments:

![image](https://user-images.githubusercontent.com/7662236/30364313-fa69779e-9863-11e7-82af-cadeb89b78ca.png)

**Comment by Ingramz** [comment]
@RonMelkhior are you sure that you have v0.41.1 installed? Try running `apm ls` to verify.

**Comment by sybrew** [comment]
@Ingramz FYI, I have v0.41.0 installed. 
I see this has been fixed in v0.41.1: #255

Cheers! 😄

**Comment by sebdesign** [comment]
How can I upgrade to 0.41.1?
I have Atom 1.20.0 but I can't see any available updates.

**Comment by Ingramz** [comment]
@sebdesign you can override the bundled version by running `apm install language-php` but you will have to run `apm uninstall language-php` later manually or else you will not receive updates when Atom receives an update. You will receive the same notice when installing.
