### ISSUE TITLE
Incorrect Brace Highlighting

### ISSUE THREAD

**Issue by mikebronner** [atom/language-php#268]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It appears that the PHP parse might not be working correctly. The following screenshots show incorrect syntax highlighting on braces:

<img width="998" alt="screen shot 2017-09-13 at 9 53 33 am" src="https://user-images.githubusercontent.com/1791050/30390026-9bf4648e-9869-11e7-87b3-866cd8ef8d26.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]
- Always

### Versions
- Atom 1.21.0-beta0
- apm  1.18.5
- npm  3.10.10
- node 6.9.5 x64
- python 2.7.10
- git 2.11.0

**Comment by Ingramz** [comment]
Fixed in v0.41.1, which has not made stable yet.

See #267 #265 etc...
