### ISSUE TITLE
foreach snippet doesn't work as expected

### ISSUE THREAD

**Issue by robballou** [atom/language-php#27]
The `foreach` snippet does not behave as expected:

Expand the snippet:

    foreach ($variable as $key => $value) {
      # code...
    }

Tab 1 is set correctly to highlight "variable". Tab 2 is set correctly to highlight "key". If tab 2 changes, tab 3 will highlight the second letter of tab 2 to the end of value instead of starting after tab 2.

![screenshot 2014-05-15 10 00 44](https://cloud.githubusercontent.com/assets/46527/2987060/22e3831a-dc4a-11e3-99de-01f4fc6d4d45.png)

**Comment by frozzare** [comment]
For me in Atom 1.0 it's like this:

- 1 tab highlight `variable` (without $)
- 2 tab highlight `key` (without $)
- 3 tab highlight `=> $value`

I think it works as it should since you maybe don't want `=> $value` each time.

**Comment by robballou** [comment]
Yeah, this seems to be fixed now. There was a snippet placeholder issue. Typing in the first placeholder wouldn't change the positions of the other markers.

As far as I can tell, this looks to be working now. My only nitpick is that tab 3 should include the space, but that would be a different issue or an easy PR https://github.com/atom/language-php/blob/master/snippets/language-php.cson#L49
