### ISSUE TITLE
[SQL] Column names incorrectly colored when prepending table alias without backticks

### ISSUE THREAD

**Issue by philraj** [atom/language-php#272]
### Description
When using table aliases to identify column names in an SQL statement, the coloring is not as it should be, unless wrapping column names with backticks:

![screen shot 2017-09-15 at 12 58 07 pm](https://user-images.githubusercontent.com/16470658/30494427-0691b190-9a16-11e7-9adf-284674497eb5.png)

### Steps to Reproduce

1. Write an SQL SELECT statement with column names prepended by table aliases, without backticks.
2. Repeat 1 without table aliases, or with backticks.
3. Notice the difference.

**Expected behavior:**
Coloring should be identical in both cases.

**Actual behavior:**
Column names are colored like PHP constants when using table aliases without backticks.

### Versions
Atom v1.20.0

**Comment by philraj** [comment]
Still present in v1.21.0.

**Comment by Ingramz** [comment]
Since PHP grammar leverages the functionality of [language-sql](https://github.com/atom/language-sql) grammar, I would suggest to move this issue there as from PHP's standpoint it works as intended.

**Comment by philraj** [comment]
Will do, thanks.
