### ISSUE TITLE
Use statement with braces

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#273]
From https://github.com/Microsoft/vscode/issues/34244#issuecomment-329987483

Not sure if this is related to https://github.com/atom/language-php/issues/246? `meta.use.php` persists unless there is a semicolon after the close brace.

```php
<?php

class Foo
{
    use A {
        B;
    }

    /**
     * Comment
     */
    private $abc;

		/**
		 * Comment 2
		 */
		 private $def;
}
```

![image](https://user-images.githubusercontent.com/323878/30515512-ff879e3c-9add-11e7-9661-77692d6be587.png)

**Comment by 50Wliu** [comment]
Very sorry for this @roblourens.  Turns out the specs I wrote only covered the `use` portion and didn't test to make sure everything following it was tokenized correctly.
