### ISSUE TITLE
quote of js regex in the php class function, breaks the highlight

### ISSUE THREAD

**Issue by gene203** [atom/language-php#282]
![screen shot 2017-09-25 at 12 43 05 pm](https://user-images.githubusercontent.com/7246630/30827494-25326848-a1ef-11e7-85b2-c389d9c90cec.jpg)

atom 1.20.0 x64, language-php 0.41.0, MacOS 10.12.6,  no additional plug-in installed.

**Comment by 50Wliu** [comment]
Fixed in Atom 1.20.1.
