### ISSUE TITLE
Non-indented php section inside script tag is not highlighted as PHP

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#289]
https://github.com/Microsoft/vscode/issues/36423

Odd issue: If I have a php section inside a script tag, it's highlighted correctly as long as the php section is indented. If it's not indented, it's not highlighted correctly. Example:

```php
<script>
<?php
	if($test){
	}
?>
	<?php
	if($test){
	}
?>
</script>
```

![image](https://user-images.githubusercontent.com/323878/31731446-f2a60102-b3e9-11e7-819e-cdf67d2db461.png)

**Comment by Ingramz** [comment]
Same as #259

**Comment by roblourens** [comment]
Oh you're probably right - different symptoms but your explanation makes them sound related.
