### ISSUE TITLE
'namespace' does not have correct classes for color coding when on same line as <?php

### ISSUE THREAD

**Issue by rtconner** [atom/language-php#29]
Here it has class="meta namespace php" correctly : http://i.imgur.com/rC11dJC.png

But when it's on the same first line as <?php (which many php coders are doing these days) the classes are missing : http://i.imgur.com/5sz1jju.png

**Comment by frozzare** [comment]
Any update on this issue?

**Comment by rtconner** [comment]
+2 lol
