### ISSUE TITLE
Switch Php Function

### ISSUE THREAD

**Issue by Galaxias** [atom/language-php#30]
Hi, 
I've recently start to try Atom.
In my last IDE, there was a auto indent function for the php switch condition.
An example:
![capture decran 2014-07-08 a 09 51 47](https://cloud.githubusercontent.com/assets/5305627/3506806/2e7a8240-0676-11e4-84e7-ddb952c80ac0.png)

**Comment by 50Wliu** [comment]
Closing in favor of #130.
