### ISSUE TITLE
Nullable return types aren't styled

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#304]
### Prerequisites

* [X] I'm using vscode

### Description

![image](https://user-images.githubusercontent.com/11234139/35065002-1c9a1f82-fbcc-11e7-838e-63eac6d6c796.png)

### Steps to Reproduce
```php
class Random {
     /**
      * Returns the start position the audio is being cutted
      *
      * @return TimeCode
      */
     public function getStart(): TimeCode {
         return $this->start;
     }

     /**
      * Returns how long the audio is being cutted. Returns null when the duration is infinite,
      *
      * @return TimeCode|null
      */
     public function getDuration(): ?TimeCode {
         return $this->duration;
     }
}
```
**Expected behavior:** 
![image](https://user-images.githubusercontent.com/11234139/35065030-381d2d94-fbcc-11e7-97ff-8f329c529fb5.png)

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/11234139/35065040-3f666e12-fbcc-11e7-81ce-30e460f032fe.png)

**Reproduces how often:** 100%

**Comment by 50Wliu** [comment]
Can there be spaces between `?` and the return type?

**Comment by jens1o** [comment]
> Can there be spaces between ? and the return type? Furthermore, does it go before or after a potential reference operator?

Yes, anything is valid:

```
class Test {
   function anythingIsAwesome()    : ? array {
        return null;
    }
}
```

**Comment by mattacosta** [comment]
It's not even colored in the default theme. 😢 

![nullable_type](https://user-images.githubusercontent.com/1007463/36941207-11e0d5e4-1f13-11e8-84d6-7fe7847be3a7.png)

> Furthermore, does it go before or after a potential reference operator?

@50Wliu A parameter is defined as: `optional_type is_reference is_variadic T_VARIABLE '=' expr` where `optional_type` can be empty, `type`, or `? type`. So to answer your question, it comes before a '&' operator.

**Comment by 50Wliu** [comment]
Thanks for the info @mattacosta, I plan to fix this in the upcoming week.

**Comment by mattacosta** [comment]
Hmm, this is still showing up as `constant.other.php` for me in the latest vscode insiders build and in atom 1.26.0-beta0.

**Comment by 50Wliu** [comment]
@mattacosta Please open a new issue, preferably with screenshots from Atom and a code example, and I will take a look.

**Comment by jens1o** [comment]
@mattacosta Are you sure the vscode team already pulled the latest updates?

**Comment by mattacosta** [comment]
Yep, they updated grammars two days ago (and pulled in b054176 I believe). I've created #320 for this as well.
