### ISSUE TITLE
Archivos  .php

### ISSUE THREAD

**Issue by juanmavillamil** [atom/language-php#306]
Hola,

Estoy desarrollando una aplicación web con Php, pero al momento de ejecutarlo en el navegador, me muestra el código, cosa que no puede pasar y desde Netbeans funciona normal...

Utilizo Xampp como emulador web y también para manejo de base de datos...

**Comment by 50Wliu** [comment]
Por favor usa https://discuss.atom.io y escribe en inglés.  Gracias!
