### ISSUE TITLE
php not recognized

### ISSUE THREAD

**Issue by Skeeve** [atom/language-php#308]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I open a file not having the extension ".php" it is not automatically recognized as php althoug it starts with "<?php"

    <?php
    $t = array(
        'potcheck_name' => 'Port Check',
        'your_ip_address' => 'Deine IP Adresse',
        'common_ports' => 'Die häufigsten Ports',
        'port_is_open' => 'Port <strong>%d</strong> ist offen',
        'port_is_closed' => 'Port <strong>%d</strong> ist geschlossen',
    );

### Steps to Reproduce

1. Take a php file like the snippet above
2. Save it as "something.lang"
3. Start atom
4. Open "something.lang"
5. Notice that the file is recognized as being "Plain Text"

**Expected behavior:** 

File should be PHP

**Actual behavior:** 

File is Plain Text 

**Reproduces how often:** 

100%

### Versions

    $ atom --version
    Atom    : 1.23.3
    Electron: 1.6.15
    Chrome  : 56.0.2924.87
    Node    : 7.4.0

    $ apm --version
    apm  1.18.12
    npm  3.10.10
    node 6.9.5 x64
    atom 1.23.3
    python 2.7.10
    git 2.14.3

    uname -a
    Darwin dhcp-140-25.lch.for-the-inter.net 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### Additional Information

See also

https://discuss.atom.io/t/better-language-recognition-please/51795

and

https://github.com/atom/language-php/pull/307

**Comment by 50Wliu** [comment]
I'm still not able to reproduce this, possibly because this was fixed by #217 (which is only included in Atom 1.24.0-beta0 and up).  @Skeeve would you mind temporarily installing [`atom-mac.zip`](https://github.com/atom/atom/releases/tag/v1.24.0-beta3) from the beta release and seeing if that helps?

**Comment by Skeeve** [comment]
Okay. Tested. It's fixed in 1.24.0-beta3
