### ISSUE TITLE
Certain string literal breaks syntax parser (end of literal is not detected)

### ISSUE THREAD

**Issue by krzysztof-sikorski** [atom/language-php#321]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

While working on some ancient software I noticed that certain string literal breaks syntax parser: the end of the literal is not detected correctly, which creates various side-effects in following code, like incorrect coloring or faulty bracket-matching.

The string was originally a long SQL query. I managed to shrink it down a bit, but I am unsure what combination of characters actually triggers the bug, as simple substrings of the "culprit" seem to be parsed correctly.

### Steps to Reproduce

1. Open a new editor tab
2. Switch language to PHP
3. Enter this code snippet:
    ```PHP
    <?php
    $sql = 'SELECT CONCAT(\'"\', TRIM(cr.code)) as code';
    $test = 123;
    ```

**Expected behavior:**

- String literal is correctly detected: it ends at semicolon, and both variable references (`$sql` and `$test`) are displayed the same way.
- Placing a cursor inside string literal on opening bracket highlights closing bracket inside the string literal.

**Actual behavior:**

![Screenshot](https://user-images.githubusercontent.com/4456257/37668986-063bd8a0-2c66-11e8-9551-f40260d4d156.png)
- String literal does not end in correct place, but "extends" further in code (see attached screenshot). On the code sample it ends in middle of next line, but in actual code I have seen it span further, even to end of file.
- Placing a cursor on opening bracket does not highlight correct closing bracket. On the snippet it does not highlight anything, on actualy code it highights some seemingly random closing bracket further in code.

**Reproduces how often:** 100%

### Versions

OS: Linux Mint 18.2 (64bit)
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.7.4

**Comment by RodCardenas** [comment]
It is the (\' sequence of characters that causes the break. I'm having the same issue.

**Comment by Arcanemagus** [comment]
Confirming this is a regression in v1.25.0, and will likely need a fix similar to https://github.com/atom/language-python/pull/243.

v1.24.1:
![image](https://user-images.githubusercontent.com/427137/37932912-95c058ce-30fe-11e8-8c62-cddf09cd0f42.png)

v1.25.0 is the same as above screenshot.

**Comment by Krinkle** [comment]
This may be related. Double quoted string with a variable and parenthesis, trips the highlighter.
```php
<?php
$sql = "DELETE FROM $delTable WHERE $delVar IN (SELECT $joinVar FROM $joinTable ";
if ( $conds != '*' ) {
	$sql .= 'WHERE ' . $this->makeList( $conds, self::LIST_AND );
}
$sql .= ')';
```

<img width="826" alt="screen shot 2018-03-30 at 17 55 20" src="https://user-images.githubusercontent.com/156867/38158123-a433e374-3443-11e8-886b-e64848697389.png">

**Comment by plandevida** [comment]
Hi all,

I see this problem with another SQL String case  "less" complicated without escaping characters.

In my case when a String contains "AND (" trips the highlighter also. For example if you chage it to "AND "."(" it works.

![captura de pantalla 2018-04-26 a las 11 06 31](https://user-images.githubusercontent.com/1167738/39296712-eed9ac70-4941-11e8-8424-c111d210bcac.png)
![captura de pantalla 2018-04-26 a las 11 06 39](https://user-images.githubusercontent.com/1167738/39296715-f22e76c6-4941-11e8-933a-8cbf4442f5d2.png)

I hope it helps.

**Comment by 50Wliu** [comment]
I've been looking into this on and off for the past few days.  Once I familiarize myself with how PHP handles SQL strings (since it seems to be more complicated than how Python does) I'll try opening a PR.

**Comment by doggonemess** [comment]
Greetings, I can say for certain that this is still happening. I have ATOM 1.52.0 x64. Below is an example of the code that breaks the syntax highlighting:

`
$query  = "SELECT DISTINCT s.locid, c.city0 city1, z.city0 city2, REPLACE(REPLACE(s.place, '.', ''), '`', '\'') as place, REPLACE(REPLACE(s.place_name, '.', ''), '\'', '') as place_name, s.st, {{svalue}} AS svalue"; 
`
 The initial `\'` breaks the syntax highlighting, and the following ones don't 'unbreak' it.

**Comment by doggonemess** [comment]
I did some tests and it is definitely the escape character with the single quote. A global replacement with a placeholder character made all of the syntax highlighting work properly; later replacing the slash-quote back in completes the code. As a temporary measure, this could actually work for me. I'm just hoping that there is a way to fix this so I don't have to jerry-rig it.
