### ISSUE TITLE
php could not be spawned

### ISSUE THREAD

**Issue by rive** [atom/language-php#323]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I installed Language-php 0.43.1 package, but I recived a message like this when open atom:
"php could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

### Steps to Reproduce

1. [Open Atom]
2. [A message occurred]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [A Error Message is displayed]

**Reproduces how often:** [100%]

### Versions

Language-php 0.43.1 on Windows

### Additional Information

I'm using Atom in Windows 10

**Comment by Arcanemagus** [comment]
This is a core Atom package, not one that is installed through the package manager.

Are you sure you weren't thinking of [linter-php](https://atom.io/packages/linter-php)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-php/issues/323#issuecomment-379092068. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
