### ISSUE TITLE
ATOM syntax highlight with comment issue

### ISSUE THREAD

**Issue by HoyeongKim** [atom/language-php#326]
hi, My Atom has a issue in PHP Syntax highlight.
![2018-04-16 2 25 35](https://user-images.githubusercontent.com/21984563/38791393-5b658070-4182-11e8-9861-5da3a233b394.png)
![2018-04-16 2 25 19](https://user-images.githubusercontent.com/21984563/38791397-5f8e3372-4182-11e8-8716-795b74ab7cb8.png)

first thing is PHP Syntax of  sublime text 3. it cleared show php code and script code.
second thing is php syntax of ATOM. but it looks like has error the syntax function.
atom cann't detact closing comment tag so below script tag also hide by comment syntax.

i'm very sorry to my wrong english.
how can i fixed it?

My atom ver is 1.25.1
and i used mac OS 10.13.4 High Sieera

**Comment by Ingramz** [comment]
@HoyeongKim thank you for the interesting bug report.

It looks like the injections in Atom's grammar include the PHP grammar to itself in this case, which should not happen. I wonder if this also happens in TextMate, which I will test in the evening.

To fix this locally, I excluded PHP source from all of the selector components:
`text.html.php - (meta.embedded | meta.tag | source.php), L:text.html.php meta.tag - source.php, L:source.js.embedded.html - source.php`, whether it is the right way of doing it, depends on the TextMate test results.

**Comment by 50Wliu** [comment]
@Ingramz any updates on your findings?

**Comment by Ingramz** [comment]
@50Wliu excluding `meta.embedded.block.php` from last two selectors should be sufficient to fix it.

Here is the injection selector that will definitely solve the problem:
`text.html.php - (meta.embedded | meta.tag), L:((text.html.php meta.tag) - meta.embedded.block.php), L:(source.js.embedded.html - meta.embedded.block.php)`
