### ISSUE TITLE
Syntax highlighting issue on PHP, JS and PHP Comment

### ISSUE THREAD

**Issue by HoyeongKim** [atom/language-php#341]
Hi, I have one problem regarding using ATOM language-php package.

![2018-11-01 10 22 13](https://user-images.githubusercontent.com/21984563/47827344-98b10f00-ddc0-11e8-91cf-ded85ed32693.png)

As you see the picture attached, the syntax highlighting function does not work properly.
How can I fix it?

**Comment by Ingramz** [comment]
I think it is the same issue you reported earlier this year, #326 

It should be sufficient to just implement the solution I provided there, I'll prepare the pull request later today.
