### ISSUE TITLE
"AND (" breaks syntax highlighting.

### ISSUE THREAD

**Issue by adjenks** [atom/language-php#349]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Old:
~~If there is PHP code in a comment, it is highlighted like normal code. This is confusing because I think that the commented code is active. It should remain in comment colour.~~
Update:
It appears that when there is the keyword AND followed by a round bracket inside of quotes, it messes everything up following it.
e.g.:
`$test = "AND (";`

### Steps to Reproduce

1. Write some PHP.
2. Add a line with this near the top of the code: `$test = "AND(";`

**Expected behavior:** Highlighting to work.

**Actual behavior:** Highlighting gets all weird.

**Reproduces how often:** 100%
### Versions
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.6.6
git 2.20.0.windows.1
visual studio

### Additional Information

None

**Comment by adjenks** [comment]
Example:
![image](https://user-images.githubusercontent.com/10687569/51275101-d8ca6b80-1985-11e9-851e-995b0b855e46.png)

**Comment by adjenks** [comment]
Looks similar to: #322

**Comment by adjenks** [comment]
Wait.. No.. I figured it out, it was a line near the beginning of my code messing up the formatting:

`$andFilters .= " AND $filterName IN ("`

It didn't like the round bracket in the double quotes. Try that out.

**Comment by adjenks** [comment]
Oh, this may be #333...

**Comment by rsese** [comment]
Thanks for the report @adjenks!  I'm not 100% but I think this may be #333 as well - we'll close in favor of that issue for now but can reopen if necessary.
