### ISSUE TITLE
Make filetype priority

### ISSUE THREAD

**Issue by m1ga** [atom/language-php#35]
I have a .php file but the first line is `<html>` so it will take "HTML" as syntax highlighting (auto). I can set it to PHP manually but it would be nice if would automatically use PHP because the file ending is .php. 

Also if I insert a blank line it will automatically use PHP

**Comment by polybuildr** [comment]
+1 Is this going to get fixed soon? It's rather annoying to have to manually change the file type to PHP so often.

**Comment by ricardograca** [comment]
I would say the autodetect feature is actually getting worse. Using Atom 0.165.0 I had no problem opening php files, with or without embeded html. It would also correctly detect `.ctp` files as php without any intervention on my part.

I just installed Atom 0.174.0 and now even files with a `.php` extension, that only have php contents are identified as `Plain Text`. `.ctp` files are always detected as `Plain Text`. If I change the grammar to PHP, it will only last for that session. Next time I open Atom it's back to `Plain Text`.

**Comment by ricardograca** [comment]
Ok, so I probably had some problem in another package that was preventing PHP files from working correctly. I did a clean reinstall of everything (removing all previous user settings) and now PHP support it seems to be working properly with the latest Atom version.

**Comment by Gloix** [comment]
I'm having this issue with version 1.1.0. I have a file ending with the .php extension and Atom recognizes it as html code. It has html and php code inside.

**Comment by Ingramz** [comment]
Fixed in 1.4.0-beta0

@50Wliu perhaps you or someone else can close this and related issues #48, #101
