### ISSUE TITLE
grammar begin/match

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#351]
Should this be `match` instead of `begin`?

https://github.com/atom/language-php/blob/608077bba25b38fdb4180af659214c2603fbbb78/grammars/php.cson#L2575

**Comment by Ingramz** [comment]
It can be either per specification, meaning if there is no `end`, it won't loop. But it would be less confusing if it was `match` instead.

**Comment by roblourens** [comment]
Fixed in #352
