### ISSUE TITLE
Wrong scope on function name that starts with 'split'

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#353]
*Edit by @rsese to add more details from comments*

> It doesn't depends on specific code, just write any function call that starts with `split` word. Any `split` occurrence at the beginning of function call name will mistakenly match `support.function.ereg.php` scope instead of `entity.name.function.php` for whole function name.

```
<?php

split_function();
splitfunction();
split();
```

![php-split](https://github-slack.s3.amazonaws.com/monosnap/test.php__worktest-tree-sitter_2019-01-25_13-49-31.png)

---

_From @esemlabel on January 21, 2019 22:24_

There pattern in `php.tmLanguage.json` for `support.function.ereg.php` scope is broken.
Every custom function that start with name split will mistakenly recognize as ereg function. This clearly visible when color scheme uses different color for builtin and custom function name:

<img width="597" alt="2019-01-22 00 22 49" src="https://user-images.githubusercontent.com/17903845/51501750-e34c9100-1ddb-11e9-8ea4-65fa97bc13f4.png">

- VSCode Version: 1.29.1
- OS Version: OS X 10.11.6 (El Capitan)

Does this issue occur when all extensions are disabled?
Yes

_Copied from original issue: Microsoft/vscode#66869_

**Comment by rsese** [comment]
Thanks @roblourens @esemlabel :+1:  Can either of you share a minimal code snippet that we can copy/paste to see the issue?

**Comment by esemlabel** [comment]
> Thanks @roblourens @esemlabel 👍 Can either of you share a minimal code snippet that we can copy/paste to see the issue?

It doesn't depends on specific code, just write any function call that starts with `split` word. Any `split` occurrence at the beginning of function name will mistakenly match `support.function.ereg.php` scope instead of `entity.name.function.php` for whole function name.

```
<?php

split_function();
splitfunction();
split();
```

**Comment by rsese** [comment]
Perfect, thanks for the extra explanation @esemlabel :v:

Reproduced with 1.34.0 on macOS 10.12.6:

![php-split](https://github-slack.s3.amazonaws.com/monosnap/test.php__worktest-tree-sitter_2019-01-25_13-49-31.png)
