### ISSUE TITLE
Syntax highlighting wrong for `::` in ternary statement

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#356]
With this code:

```php
<?php
true ? A::a : A::b;
```

See that the first `:` is colored differently from the second, because it is interpreted as the `:` in the ternary statement.

![image](https://user-images.githubusercontent.com/323878/53266997-2cbc2480-3697-11e9-9efb-80489a39573c.png)

https://github.com/Microsoft/vscode/issues/69156

*Edit by @rsese to add Atom screenshot*

![php-ternary](https://github-slack.s3.amazonaws.com/monosnap/test.php__worktest-tree-sitter_2019-02-25_18-06-53.png)

**Comment by rsese** [comment]
:+1: reproduced with 1.34.0 on macOS 10.12.6:

![php-ternary](https://github-slack.s3.amazonaws.com/monosnap/test.php__worktest-tree-sitter_2019-02-25_18-06-53.png)
