### ISSUE TITLE
Should this package include, php functions autocompletion like array_push?

### ISSUE THREAD

**Issue by Cipa** [atom/language-php#36]
Hi,
When I type array shouldn't I get a list of array functions, and when I select one shouldn't I get, for example
array_push(array &$array , mixed $value1)

Can the above be done in language-php.cson file or is this out of the scope of the file? 
If I want to do my own php autocompletions should I edit this file or something else?

Thanks

**Comment by kevinsawicki** [comment]
This package handles syntax highlighting and snippets, it looks like you want to install https://atom.io/packages/autocomplete-php to get improved autocompletions, closing this out.
