### ISSUE TITLE
Default array value syntax error with class constants

### ISSUE THREAD

**Issue by mundschenk-at** [atom/language-php#363]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When there's an `array` type hint for a method/function parameter, the use of (class) constants is flagged as a syntax error. Removing the `array` fixes it. This is similar to #64.

![image](https://user-images.githubusercontent.com/6943905/60606163-25322800-9dbb-11e9-9bd5-ec0da131a14a.png)

![image](https://user-images.githubusercontent.com/6943905/60606180-2d8a6300-9dbb-11e9-95ef-37fff3a05481.png)

(`self::DEFAULT_CHARACTER_MAPPING` being defined as a constant array.)

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.10
git 2.21.0

macOS 10.14.5

**Comment by rsese** [comment]
Thanks for the report!  Example typed out for copy/paste (it's always helpful for us if you can share  the full minimal example for copy/pasting):

```php
<?php 
public function __contruct( $set_defaults = true, array $mapping = self::DEFAULT_CHARACTER_MAPPING ) {
  
}
?>
```

The scopes with the cursor in "DEFAULT_CHARACTER_MAPPING":

![php-error](https://user-images.githubusercontent.com/734194/60745420-bb8f5680-9f3f-11e9-9c5e-afaad0abbfa9.png)

Reproduced on macOS 10.12.6 with 1.40.0-nightly19.
