### ISSUE TITLE
The use operator and optional semicolon before closing tag

### ISSUE THREAD

**Issue by sineway** [atom/language-php#364]
*Edit by @rsese to use the issue template*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The `use` operator without optional semicolon before closing tag breaks syntax highlighting.

### Steps to Reproduce

1. Create a PHP file and enter:

```php
<?php use Some\Name ?>

<article class="article">
</article>
```

**Expected behavior:**

Correct highlighting with/without the semicolon in line 1, i.e. the file will highlight correctly with the semicolon in line 1:

```php
<?php use Some\Name; ?>

<article class="article">
</article>
```

**Actual behavior:**

![Peek 2019-07-04 16-05](https://user-images.githubusercontent.com/23264894/60670134-9683e080-9e78-11e9-8b4d-780a7fd95704.gif)

**Reproduces how often:**

100%

### Versions

1.40.0-nightly25 on macOS 10.14

### Additional Information

---

**Current behavior**

![Peek 2019-07-04 16-05](https://user-images.githubusercontent.com/23264894/60670134-9683e080-9e78-11e9-8b4d-780a7fd95704.gif)

**Expected behavior**
Highlight regardless semicolon

**Comment by rsese** [comment]
Thanks for the report @sineway, reproduced with 1.40.0-nightly25 on macOS 10.14.  For future issues, please use the issue template or your issue may be closed - the information in the template is super helpful for us when triaging issues.
