### ISSUE TITLE
Return types uncolored w/ anonymous functions 

### ISSUE THREAD

**Issue by KapitanOczywisty** [atom/language-php#367]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Return types from anonymous functions are not correctly colored.

### Steps to Reproduce

1. Use this code:

```php
<?php

function a(): string {
	return '';
};
$a1 = function ($a): string {
	return '';
};
$a2 = function &($a): string {
	return '';
};
$b1 = function () use($a1): string {
	return '';
};
$b2 = function &() use($a1): string {
	return '';
};
```

**Expected behavior:**

Correct colors for `: string` with anonymous function

**Actual behavior:**

![image](https://user-images.githubusercontent.com/44417092/63883571-c1039d00-c9d4-11e9-8189-a5d1d3ce09d7.png)

Notice that in ~~$b1~~ $a2 (sorry) `:` has wrong color and `string` is colored by some other rule.

**Reproduces how often:** always 

### Versions

atom 1.40.1
language-php 0.44.2
also:
vscode 1.37.1

### Additional Information

Similar issue #343 
Originally reported: https://github.com/bmewburn/vscode-intelephense/issues/640

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify:

> Notice that in $b1 `:` has wrong color and `string` is colored by some other rule.

Should it be the same as the `:` in line 3?

Also, is the only issue you're reporting with line 12 or are there issues with the other functions (I see 3 different `string` colors, `$a1` is different on lines 12 and 15, and the `return` on line 16 doesn't seem to be treated as a keyword)?  Just want to make sure we're on the same page with what you're reporting.

**Comment by KapitanOczywisty** [comment]
Sorry, I meant `$a2` / line 9 instead of `$b1`.

I'm reporting return type colors - mainly `$a1`, `$b1`. There is also problem with `$a2`, `$b2`, but they are reported in separate issue #343 and here included just to be aware of such syntax.

So focus on lines `6` and `12`

**vscode** colors are even more wild than atom:
![image](https://user-images.githubusercontent.com/44417092/63922323-c4cf0800-ca44-11e9-86c9-3779a3c8868f.png)

Void highlights incorrectness of `$a2` (still **vscode**)
![image](https://user-images.githubusercontent.com/44417092/63922339-cac4e900-ca44-11e9-9e44-1598fb799e50.png)
and from **Atom**:
![image](https://user-images.githubusercontent.com/44417092/63922498-18415600-ca45-11e9-8abb-b9cf4e0bcad5.png)
