### ISSUE TITLE
Code highlighting color issue for PHP for function named "fn"

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#401]
From https://github.com/microsoft/vscode/issues/105742

![Schermata 2020-08-31 alle 17 19 09](https://user-images.githubusercontent.com/5537554/91737069-de9eb000-ebae-11ea-814a-86b79128d8f0.png)

```
<?

function fn(){
	// do something
};

?>
<div><?=fn()?></div>
```

**Comment by KapitanOczywisty** [comment]
@ottopic @roblourens It's reserved since PHP 7.4 https://3v4l.org/T4SHV

Docs:
https://www.php.net/manual/en/functions.arrow.php
https://www.php.net/manual/en/reserved.keywords.php

**Comment by sadick254** [comment]
Closing this for now based on the https://github.com/atom/language-php/issues/401#issuecomment-685861694 and the PHP docs pointed to.
