### ISSUE TITLE
Highlighting fails after 23th item in array

### ISSUE THREAD

**Issue by wasinwill** [atom/language-php#410]
It looks like there's a maximum number of variables (23 exactly) one can put in an array before recognition fails. Starting from the 24th item, text is just added as a string with no `span` tag to style.

![capture](https://user-images.githubusercontent.com/44789688/103569833-02903c00-4e96-11eb-8bb4-044b982df420.png)

![dev](https://user-images.githubusercontent.com/44789688/103569636-a75e4980-4e95-11eb-9198-b77a2d163e7a.png)

Not sure if it's a bug or a limitation...

---
Version 1.53.0 x64
Electron 6.1.12
Chrome 76.0.3809.146
Node v12.4.0
Theme One Dark

**Comment by KapitanOczywisty** [comment]
@wasinwill Can you provide code as a text for easier reproduction?

**Comment by Ingramz** [comment]
Another case of https://github.com/atom/atom/issues/1667

Not a bug of the grammar in this repository.

**Comment by KapitanOczywisty** [comment]
This limit is way too low. In VS Code I have 1000 variables in single line and syntax is still working fine.

**Comment by KapitanOczywisty** [comment]
![image](https://user-images.githubusercontent.com/44417092/103577042-5e79b580-4ed4-11eb-84b8-a840d1a3dcb5.png)

It should be possible to make extension to tweak that.. hmm 😛

**Comment by wasinwill** [comment]
> @wasinwill For the future: can you provide code as a text for easier reproduction?

Absolutely. Sorry about that.

**Comment by wasinwill** [comment]
@KapitanOczywisty That did it! Thanks!
