### ISSUE TITLE
The $ sign is not in the nonWordCharacters but the highlight still ignoes it

### ISSUE THREAD

**Issue by Sofianio** [atom/language-php#413]
### Steps to Reproduce

1. Double click or cmd+D to select a variable `$variable`

**Expected behavior:**

2. should select the whole variable 

**Actual behavior:**

3. only `variable` selected the $ sign not included

**Reproduces how often:**

Every tIme

### Versions

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
### Additional Information

The $ sign is not in the nonWordCharacters
> /\()"':,.;<>~!@#%^&*|+=[]{}`?-

I tried launching atom via `atom --safe` but found same behavior

**Comment by KapitanOczywisty** [comment]
https://github.com/atom/language-php/issues/92#issuecomment-765348037 and subsequent comments.

**Comment by Sofianio** [comment]
Thanks, that does it

Reference: 
>To quick-fix this you have to set Non Word Character globally in Editor Settings - remove $ from the list.
