### ISSUE TITLE
"extends" Interface name after newline not highlighted

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#414]
Related to https://github.com/microsoft/vscode/issues/113185, https://github.com/microsoft/vscode/issues/116103

```php
interface Blah
extends Blue {
}
```

Removing the newline before "extends" fixes it. With the newline, "Blue" has 

![image](https://user-images.githubusercontent.com/323878/107443270-5fae8b80-6aed-11eb-970b-a2fa3a082578.png)

**Comment by KapitanOczywisty** [comment]
Confirmed, though It's not related to previous issue. Interface definition is a big mess I'll try to get around to it, but if somebody is interested: 
https://github.com/atom/language-php/blob/9b703d88b485b91ee40be8117668f18ee92fbebb/grammars/php.cson#L17-L47
Interface definition should be similar to class
https://github.com/atom/language-php/blob/9b703d88b485b91ee40be8117668f18ee92fbebb/grammars/php.cson#L206-L324
