### ISSUE TITLE
PHP $ symbol wrong color after last update

### ISSUE THREAD

**Issue by ElderTugBoat786** [atom/language-php#423]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After the last update when i open or create a php file with php grammar selected all $ are white and not red ( like previous version)

### Steps to Reproduce

1. create a new .php file
2. declare random variabile

**Actual behavior:**

![image](https://user-images.githubusercontent.com/38555796/115002788-6ff43580-9ea5-11eb-86d0-68fd9a63d57f.png)

### Versions

Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

### Os info
Edition : Windows 10 Pro
Version ; 20H2
Build number : 19042.867

Thanks for the support.

**Comment by KapitanOczywisty** [comment]
Hi @ElderTugBoat786  , I'm unable to reproduce this. Can you place cursor before `$` then run command (Ctrl+Shift+P) `Editor: Log Cursor Scope` and copy what you get in right bottom corner?

**Comment by ElderTugBoat786** [comment]
Hi @KapitanOczywisty 

Scopes at Cursor

  - text.html.php
  - meta.embedded.block.php
  - source.php
  - variable.other.php
  - punctuation.definition.variable.php

This is the notification text. I have tried also in safe mode but text is the same,

**Comment by KapitanOczywisty** [comment]
@ElderTugBoat786  Scope looks good, so I suspect theme is responsible for this change. Which `Syntax Theme` are you using?

**Comment by ElderTugBoat786** [comment]
My current Syntax Theme is One Dark.  

I have found this if it could be useful

![image](https://user-images.githubusercontent.com/38555796/115032300-709ec300-9ec9-11eb-9096-66007ed47999.png)
![image](https://user-images.githubusercontent.com/38555796/115032374-857b5680-9ec9-11eb-9bbd-feec0f76e416.png)

**Comment by KapitanOczywisty** [comment]
I think that this is result of this PR https://github.com/atom/atom/pull/20524 I'd suggest reporting issue there and request to change this back for php or if you know `less` syntax making own PR with changes probably here: https://github.com/atom/atom/blob/master/packages/one-dark-syntax/styles/syntax-legacy/php.less

**Comment by ElderTugBoat786** [comment]
Hi @KapitanOczywisty 
I have wrote a comment on that PR.
I close the issue as I don't think it concerns this repo

Thanks for the support.
