### ISSUE TITLE
Remove $ from nonWordCharacters

### ISSUE THREAD

**Issue by joshuajabbour** [atom/language-php#43]
Now that [Language Specific Configuration Settings](http://blog.atom.io/2014/10/31/language-scoped-config.html), have landed, should we consider removing `$` from `nonWordCharacters`? How often does one want to select only the text of a variable name, and not the dollar sign too?

**Comment by narf** [comment]
Ideally, when double clicking on a word, the it should select the full token depending on the language and position of the word.

double click on:
variable -> full var
number -> full number
text -> word

etc...
But this is probably quite a big change.

Changing non-word char in config is a quick fix that can work but to make it easier, could there be a copiable default regex ? Actually it's quite a pain to just remove one character, i have to find the default regex on internet, copy it paste it, remove the $. Or if i can't find it on internet, make a screen, then copy them by hand...

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/language-php/pull/75
