### ISSUE TITLE
Parser not handling

### ISSUE THREAD

**Issue by bsides** [atom/language-php#44]
This is an example from the system I'm working on. Please refrain from the style, I know it's horrible but since it's a legacy system not much can be done.

Anyway, this is a good example, because it's a hard thing for a parser to get this working - but it does work in other editors (ie: Sublime).

Could you please tell me what could I do to make it work? In case you didn't notice, the HTML code coloring is good in the beggining but whenever you reach the end of the image, near ```<?php endif; ?>```, the HTML coloring is gone forever and the rest of the document is interpreted as being between quotes.

The images attached are from Atom and then Sublime, respectively (both Ubuntu 14).

Thanks in advance.
![selecao_016](https://cloud.githubusercontent.com/assets/87631/5053335/691af0b8-6c30-11e4-8d0f-6a679a3a79db.png)
![selecao_017](https://cloud.githubusercontent.com/assets/87631/5053352/8c3019ac-6c30-11e4-9584-4feab74f8e13.png)

**Comment by izuzak** [comment]
> Is the `<a onclick` just one big long soft-wrapped line? If so, I suspect this is a duplicate of atom/atom#1667. Atom currently only syntax highlights 100 tokens per line.

I'm pretty sure that's the case here. Closing in favor of atom/atom#1667.
