### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by IonBazan** [atom/language-php#447]
I noticed new PRs are not being merged for a while already. It seems that @sadick254 is no longer actively maintaining it, which I totally understand but maybe it's time to look for a new maintainer in that case?

While finding a new maintainer is a difficult task, I would suggest granting @KapitanOczywisty maintainer permissions (as long as he is OK with that), as he is actively contributing to the project by adding new features triaging the issues.

Any thoughts?

**Comment by crvllws** [comment]
Sound quite lovely!

**Comment by KapitanOczywisty** [comment]
Microsoft is taking resources off from atom development, so probably they are overwhelmed with tasks. As for maintainer, not sure if they even allowed to do that, but even then there is little to no interest in approving changes in community, and I wouldn't want to merge my PRs without second opinion.

**Comment by crvllws** [comment]
to be honest I have no idea how to do that. struggling getting my ssh pub key set up been struggling ALL bloody day...

**Comment by crvllws** [comment]
How do you do any of what you suggested? Like granting @KapitanOczywisty permissions to do more the editing that I am lacking on keeping up with =/

**Comment by IonBazan** [comment]
@KapitanOczywisty the reason I created this ticket is that https://github.com/github/linguist (tool used by GitHub for syntax highlighting) could benefit from all the recent changes you've made, including new PHP 8 features support.

Another option is to create and maintain a fork combining all the new features and linking it into Linguist.

**Comment by KapitanOczywisty** [comment]
VSCode is relaying on this repository, so they could fork this, however this will probably be the last resort. For now I've contacted someone in ms directly.

> Another option is to create and maintain a fork combining all the new features and linking it into Linguist.

It could be another dead fork in a while, the best would be to move this to vscode, since atom is slowly moving towards tree-sitter anyway. As always everything is relaying on people willing to maintain the code.
