### ISSUE TITLE
Support enum keyword

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#451]
Have code like

```php
<?php
enum Status : string
{
    case VALID = 'VALID';
    case NOT_FOUND = 'NOT_FOUND';
}
```

This is apparently a new PHP feature. `enum` is not colored. I think I expect a similar token to "class"

https://github.com/microsoft/vscode/issues/142824

**Comment by KapitanOczywisty** [comment]
I'm working on it, PR should be up soon.
