### ISSUE TITLE
Atom Snippet Tab Stops Not Working Correctly

### ISSUE THREAD

**Issue by realph** [atom/language-php#46]
So I'm trying to create a snippet for .js files. And I want a snippet that looks like this:

    $scope.TAB1(TAB2, function(TAB3) {
        TAB4
    });TAB5

So, my snippet looks like this, naturally:

        'Angular Scope':
            'prefix': 'scope'
            'body': '$scope.${1}(${2}, function(${3}) {
              ${4}
            });$5'

But for some reason it jumps from tab stop 1, to tab stop 3, to tab stop 5. The white space is also ignored. Is there any way around this? Any help is appreciated. Thanks!

**Comment by Arcanemagus** [comment]
How does this relate to `language-php`?

**Comment by 50Wliu** [comment]
Agreed, this does not seem to be related to language-php.  If you are still having problems, please create a new topic on https://discuss.atom.io.
