### ISSUE TITLE
Highlighting parentheses

### ISSUE THREAD

**Issue by kmfk** [atom/language-php#47]
I tried taking a stab at adding this in the `php.cson` file - but didn't get far.

Things like `if(true)` or `case($foo)`, or native functions `in_array()` - the parentheses are not wrapped in a span with a class(es), meaning we can't target them in syntax themes.

Example from the dom on an if statement checking a `file_exists`: [source](https://www.dropbox.com/s/uilh6kiy3ip7eul/Screenshot%202014-12-03%2017.07.06.png?dl=0)

Can this be added?  I'll keep digging through the language file in the meantime.

**Comment by 50Wliu** [comment]
Progress.  Just need to fix/add specs and then I'll submit a PR.

|Before|After|
|-------|-----|
|![php-before](https://user-images.githubusercontent.com/2766036/26961025-9f40a7b2-4ca9-11e7-8d55-0bf44302cd54.png)|![php-after](https://user-images.githubusercontent.com/2766036/26960997-667b1d9a-4ca9-11e7-8196-19e2ffb4cd55.png)|
