### ISSUE TITLE
PHP Syntax Highlighting not working if file has <!DOCTYPE html> in the first line

### ISSUE THREAD

**Issue by BlaM** [atom/language-php#48]
Atom seems to decide that files are "pure HTML" when they have <!DOCTYPE html> in their first row.

This seems even then to be true if it looks like this:

    <?PHP echo '<!DOCTYPE html>';

In that case PHP code is not syntax highlighted.
Whenever I move the <!DOCTYPE to row 2 everything is back to intended (after reloading the file).

**Comment by RanSolo** [comment]
I can second this issue, did not know I could fix it just by dropping it a line, thanks!

**Comment by sxss** [comment]
Same here.

**Comment by wasserbombe** [comment]
Same here... This bug should be fixed!

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.4.0-beta0.  If it isn't please comment here!
