### ISSUE TITLE
Comment highlight breaks when it contains a closing and opening php tag

### ISSUE THREAD

**Issue by Kaperstone** [atom/language-php#51]
Well, basically the titles says all, took a screenshot -
![img_17102014_121914](https://cloud.githubusercontent.com/assets/8384463/5463134/ca59e9ea-8582-11e4-837d-1eb99640552a.png)

Text : 

`<?php /* print_r($session); ?>|<?php print_r($user); */ ?>`

**Comment by Devian50** [comment]
Is it possible to rename the issue, as I found myself falling subject to the same issue. `<script>` tags interfere with php highlighting, at least in files set to the PHP language. They are instead highlighted using javascript highlighting.  
![2015-07-14_00-46-14](https://cloud.githubusercontent.com/assets/767190/8666630/4d079a5c-29c2-11e5-81b7-58c3f40b3c36.png)

**Comment by Terail** [comment]
Sorry for reviving this very old thread. I got odd highlighting issues in PHP scripts, which are using "long-type comments" when used like this:

`<?php /* ?> some temporary hidden output here <?php */ ?>`

Odd thing is, that everything after the <?php */ ?> Tag still is highlighted as "comment block", just until the end of the file. Can this easily been fixed? I do not have this highlighting issue in UltraEdit, BBEdit or Brackets. Using the latest version 1.5.4 of Atom on OSX.

**Comment by 50Wliu** [comment]
The PHP-not-working-in-script-tags issue was fixed in Atom 1.12.0 (if I remember correctly) and should work correctly now.
