### ISSUE TITLE
PHP syntax parse error

### ISSUE THREAD

**Issue by voylinux** [atom/language-php#55]
When makin an intensive use of simple quotes and contatenations in a long PHP file, the syntax highliter seems not to work ok.

Shows many sections of the file as commented or strings.

**Comment by 50Wliu** [comment]
Do one of the lines in the PHP file have more than 100 characters?

**Comment by voylinux** [comment]
One of them has more than 100 characters.
But the syntax breaks for a big part of the file, not just that line.

**Comment by 50Wliu** [comment]
Yes, that is a known bug that is documented at atom/atom#1667 (with a potential fix at atom/first-mate#33).
