### ISSUE TITLE
Auto-Complete Commenting.

### ISSUE THREAD

**Issue by Lynxaa** [atom/language-php#56]
Hey, this is something I feel would enhance the experience for many users using the PHP editor in At0m.

Make it so that when you open a comment, e.g ```/**``` make it auto-complete it.

e.g
```
	/**
	 * 
	 *
	 *
	 */
```

This type of stuff is very useful in IDE's like Eclipse, Netbeans, etc.
Another suggest would be once this feature is implement allow the user to choose to add stuff like,
@author 
@date <date this file was commented/made
@version
@see
etc.

**Comment by 50Wliu** [comment]
This should probably belong in the [autocomplete](https://github.com/atom/autocomplete) repo.

**Comment by Lynxaa** [comment]
Oops, sorry.
Didn't know that repo existed :P
I'll move this issue over to there.
