### ISSUE TITLE
snippet not working on atom v0.177

### ISSUE THREAD

**Issue by lce-fr** [atom/language-php#59]
Hello everyone,

I wanted to try language-php snippets but nothing happens when I type 
class + tab in  test.php file. No error.

I tried to remove the symfony package (in case of conflict) but it still does not work. Remark : html and react snippets works.

config : 
VM debian 7 64 bits
atom v0.177

**Comment by lee-dohm** [comment]
PHP is an embedded language, when you open a brand new file, the scope is `.text.html.php` ... essentially being in "HTML mode". If you type `php` and press <kbd>TAB</kbd>, then the standard PHP block shows up: `<?php  ?>`. Inside that block, the scope is `.source.php` and snippets like `def`, `class` and others are now available.

If you look at the raw snippets list:

https://github.com/atom/language-php/blob/master/snippets/language-php.cson

You'll see that they are subdivided based on whether they are available in HTML mode or PHP mode.

**Comment by lce-fr** [comment]
Indeed, sorry for being that dumb and forgetting to add <?php. in my file.

Thank you

**Comment by lee-dohm** [comment]
Don't worry about it! We all have moments where things like this slip our minds :grinning:
