### ISSUE TITLE
[PHP] Syntax highlighting for inline variables

### ISSUE THREAD

**Issue by lee-dohm** [atom/language-php#61]
_From @Verox- on February 12, 2015 22:59_

![Issue example](http://i.imgur.com/lzUxSyj.png)

As shown in the image, OO style function calls surrounded by curly braces in strings doesn't format properly.

_Copied from original issue: atom/atom#5532_

**Comment by lee-dohm** [comment]
_From @50Wliu on February 12, 2015 23:2_

Could you please report this to the [language-php](github.com/atom/language-php) repository?  Thanks.

**Comment by 50Wliu** [comment]
Closing in favor of #109.
