### ISSUE TITLE
An apostrophe placed in a single line results in the rest of the file being treated as a comment

### ISSUE THREAD

**Issue by FaridW** [atom/language-php#68]
This is one code example that triggers the issue:

```php
// Set address name if it wasn't entered
if (!$location->getAddressOne() && $location->getAddressTwo())
{
	$location->setAddressOne($location->getAddressTwo() ? ' ' . $location->getAddressTwo() : '');
}

$hasAddress = $location->getAddressOne() ? true : false;
```

Changing the first line of the code to remove the apostrophe corrects the problem:

```php
// Set address name if it wasnt entered
if (!$location->getAddressOne() && $location->getAddressTwo())
{
	$location->setAddressOne($location->getAddressTwo() ? ' ' . $location->getAddressTwo() : '');
}

$hasAddress = $location->getAddressOne() ? true : false;
```

**Comment by lee-dohm** [comment]
I'm having trouble reproducing this issue using Atom v0.193.0-af5618e on Mac OS X 10.10.3:

![screen shot 2015-04-20 at 5 38 00 pm](https://cloud.githubusercontent.com/assets/1038121/7243601/0540c50c-e784-11e4-97ed-aa1b00e79f49.png)

Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by FaridW** [comment]
I'm using Atom 0.192.0, I've seen issue on 10.10.3 and 10.10.4 (my current version).

I cannot reproduce the issue after restarting using ```atom --safe```, thanks for that. Does that clear a cache that would have persisted the problem after it was resolved?

**Comment by lee-dohm** [comment]
It doesn't clear a cache, but it does run Atom with only the default-installed packages. It is the fastest way to determine if an issue is due to Atom itself or a third-party package.

**Comment by FaridW** [comment]
After toggling packages off and back on, I tracked down the package causing the issue which is not by any means PHP-related but is definitely the source of the problem.

Thank you for the helpful explanation, I'll post this issue there now.

**Comment by lee-dohm** [comment]
You're very welcome! I'm glad that I could help :grinning:
