### ISSUE TITLE
PHP sytax not being highlighted

### ISSUE THREAD

**Issue by ChristianGrech** [atom/language-php#71]
Everything was working fine and I've been using atom for the past month. Althoguh, somehow the syntax of php and only php is not being highlighted. If I change the file type to C or C++ it will be highlighted according to the language, however, php is not.
![image](https://cloud.githubusercontent.com/assets/4950218/7522015/ab131860-f4f2-11e4-9dab-304feaa23d77.png)

**Comment by mnquintana** [comment]
This has been fixed in Atom 0.198.0
