### ISSUE TITLE
Syntax Highlighting issue

### ISSUE THREAD

**Issue by adibhanna** [atom/language-php#86]
Hello, when i open a php file in atom v1.0 sometimes i don't see any highlighting

**Comment by screeny05** [comment]
can't confirm this. i'm on atom-1.0 and everything is working fine for me

**Comment by UNADINE-CORPORATION** [comment]
I can I am building a custom cms and have several files open at the same time. Some files show highlighting and some don't.

**Comment by 50Wliu** [comment]
Closing issue as stale - if someone is still experiencing this please open a new issue and fill out the issue template.  Thanks!
