### ISSUE TITLE
Syntax Highlighting Issue on class methods

### ISSUE THREAD

**Issue by dangerousdan** [atom/language-php#91]
The last argument in a class method has no syntax highlighting when the closing parenthesis is on a new line (as in the PSR-2 standard). See L9 in the screenshot

![image](https://cloud.githubusercontent.com/assets/5559301/8874703/2f35f2b6-320b-11e5-938f-0ddfd6c46463.png)

Note: If the last argument is typehinted or assigned a value, then the highlighting functions as expected

**Comment by UNADINE-CORPORATION** [comment]
How about when using php in an html page?  There is no highlighting when the html header is directly set on the page.

**Comment by 50Wliu** [comment]
```php
class Example
{
  public function correct(Foo $var1, $var2) {}
  public function incorrect(
    Foo $var1, $var2
  ) {}
  public function correct(
    Foo $var1, $var2 = null
  ) {}
  public function correct(
    Foo $var1, Foo $var2
  ) {}
```
Looks like this got fixed somewhere along the way.
![php-newline-arguments](https://user-images.githubusercontent.com/2766036/26961780-5ad67a06-4caf-11e7-9791-81000f40d0e1.png)
