### ISSUE TITLE
Unrelated suggestions

### ISSUE THREAD

**Issue by Dgame** [atom/language-php#93]
Consider this Code:

```php
<?php

class Bar {
    public $var_abc = null;
    public $var_xyz = null;
    public $var_foo = null;

    public function foourz() { }
}

class Foo {
    public function foobar($a) {
        return new Bar();
    }

    public function test() {

    }
}

$f = new Foo();
```

If I type `$f->f`I get many unrelated suggestions (like `for`, `foreach`, `fopen`etc) and even for those identifiers which aren't in `Foo`(e.g. `foourz` from Bar. Is this intended?

**Comment by kevinsawicki** [comment]
> Is this intended?

Yeah, currently autocompletions by default uses all the words in the editor in the popup list.

If you have suggestions for improving this, please open an issue on the https://github.com/atom/autocomplete-plus repository, thanks.
