### ISSUE TITLE
Closure start has no scope.begin but closure end has scope.end. (Bug?)

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [atom/language-php#98]
Hello

I noticed something odd with the CSS classes: it appears for function definitions, the opening brace gets class `punctuation section scope begin php` and the closing brace `punctuation section scope end php`, but it seems that closures are not treated the same way; the closure opening brace gets class `meta function closure php` but its closing brace suddenly does get `punctuation section scope end php`? This means that the amount of scope starts and ends are not equal if there are closures. See also [1] for an example.

Is this a bug?

Thanks in advance

[1] https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/3e6e771a05968ce842904fa4d004b75fdaa11421/src/TestNamespace/SomeClass.php#L298

**Comment by Ingramz** [comment]
Yes it's a bug.

https://github.com/atom/language-php/blob/master/grammars/php.cson#L948-L973

The problem should auto-resolve if the "end" part of the rule didn't match `{` but did a positive lookahead instead.
