### ISSUE TITLE
Make .twig files open with PHP syntax

### ISSUE THREAD

**Issue by alexandernst** [atom/language-php#99]
.twig files are basically PHP files, it would be nice if they could be opened with PHP syntax/highlighting by default.

The `.twig` extension should be added here: https://github.com/atom/language-php/blob/befafefa06df28386f33a62bc0ab32bbb289f3b8/grammars/php.cson#L3-L17

**Comment by Ingramz** [comment]
There are packages available which provide functionality for php-twig

https://atom.io/packages/php-twig
https://atom.io/packages/language-twig

As far as I know twig is not a subset of PHP, so trying to match it with this grammar could result in unexpected behavior.

**Comment by alexandernst** [comment]
Wasn't aware of that.
